import {typeContexts,contextHeadings} from './type-contexts';
import {dopeContexts} from './dope-contexts';
import {relationshipGuides} from './relationship-guides';
import {typeProfiles,typeHeadings,type TextPair} from './type-content';
export type Section = {heading:TextPair;body:TextPair};
export type ContentPage = {path:string;title:TextPair;description:TextPair;sections:Section[];links:string[];kind?:'guide'|'type'|'hub';index?:boolean;published?:string;updated?:string};
const s=(heading:TextPair,body:TextPair):Section=>({heading,body});
const dopeProfiles:ContentPage[]=[
 {path:'/dope/dove',title:['鴿子型：用同理建立清楚的溝通','Dove style: empathy with clear communication'],description:['認識 DOPE 鴿子型的聆聽優勢、界線挑戰與團隊相處，練習在照顧別人時也表達自己。','Explore the Dove style’s listening strengths, boundary challenges and teamwork, with ways to express your needs while caring for others.'],kind:'type',links:['/dope','/dope/eagle','/dope/owl','/guides/communication-differences'],sections:[
 s(['鴿子風格是甚麼？','What is the Dove style?'],['在 Twynzo 的 DOPE 測驗中，鴿子代表重視理解、耐心與關係的選擇。你可能先留意大家是否舒服，才推進討論。這是本次回答的溝通輪廓，不是固定身份。','In Twynzo’s DOPE quiz, Dove represents choices focused on understanding, patience and relationships. You may check how comfortable people feel before moving a discussion forward. This is a profile of the answers, not a fixed identity.']),
 s(['優勢：讓人願意開口','Strength: making room for people to speak'],['願意聽完、不急著判斷，能讓比較安靜的人說出重要資訊。團隊遇到分歧時，你可以先整理共同關心的事，再把不同需要放到桌上討論。','Listening without rushing to judge can help quieter people share important information. During disagreement, summarize the shared concern before putting different needs on the table.']),
 s(['挑戰：和平不等於沒有問題','Challenge: peace is not the absence of a problem'],['為免衝突而答應所有要求，可能把壓力留給自己。若你需要更多時間，可以說：「我想幫忙，但今天只能完成這部分。」清楚界線能讓關係更可持續。','Agreeing to every request to avoid conflict can leave you carrying the pressure. Try “I want to help, but I can finish only this part today.” Clear boundaries can make support more sustainable.']),
 s(['團隊合作與溝通','Teamwork and communication'],['在會議中保留聆聽，同時把自己的建議說在前面，再解釋對人的影響。和偏老鷹風格的人合作時，提出一個具體方案和決定期限，讓關心能轉成行動。','Keep listening, but lead with your own recommendation and then explain its effect on people. With someone using an Eagle-like approach, offer a concrete option and decision time so care can become action.']),
 s(['人際關係中的互相照顧','Reciprocal care in relationships'],['你可能容易察覺對方的心情，但不要只靠猜測需求。詢問對方想被聽見還是需要協助，也讓對方知道你何時需要支持。照顧應該可以雙向流動。','You may notice another person’s mood, but avoid relying on guesses about their needs. Ask whether they want listening or help, and tell them when you need support too. Care can move in both directions.']),
 s(['一個可實行的練習','One practical exercise'],['下一次不同意時，先說共同目標，再說自己的需要，最後提出替代方案。例如：「我也想準時完成，但今晚需要休息；我們可以明早一起確認。」','The next time you disagree, name the shared goal, your need and an alternative. For example: “I want us to finish on time too, but I need rest tonight. Could we review it together tomorrow morning?”']),
 ]},
 {path:'/dope/owl',title:['貓頭鷹型：把仔細思考化為清楚建議','Owl style: turn careful analysis into clear advice'],description:['了解 DOPE 貓頭鷹型如何運用細節與證據，避免無止境分析，並在團隊和關係中清楚溝通。','Learn how the Owl style uses details and evidence, avoids endless analysis and communicates clearly in teamwork and relationships.'],kind:'type',links:['/dope','/dope/peacock','/dope/dove','/guides/communication-differences'],sections:[
 s(['貓頭鷹風格是甚麼？','What is the Owl style?'],['貓頭鷹代表先釐清資訊、比較理由與檢查細節的選擇。你可能對模糊指示特別有疑問，因為希望知道怎樣才算完成；這不代表其他風格不理性。','Owl represents choices to clarify information, compare reasons and check details. Vague instructions may prompt questions because you want to know what completion means. Other styles are not therefore irrational.']),
 s(['優勢：讓品質可以被檢查','Strength: making quality checkable'],['把規格、風險和假設說清楚，能減少重做。團隊在選方案時，你可以指出哪一項仍是猜測，並建議最值得補充的資料。','Clarifying requirements, risks and assumptions can reduce rework. When a team selects an option, identify what remains a guess and which information would be most useful to obtain.']),
 s(['挑戰：資料永遠可以更多','Challenge: there is always more information'],['持續比較可能延後決定。先問「還缺的資料會改變選擇嗎？」若不會，把限制記下，設定可接受風險與檢查時間，再前進。','Continual comparison can delay a decision. Ask whether the missing information would change the choice. If not, document the limitation, agree on acceptable risk and a review time, then proceed.']),
 s(['團隊合作與溝通','Teamwork and communication'],['先說建議，再列最關鍵的兩個理由，把完整資料留作補充。和偏孔雀風格的人合作時，先肯定點子的目標，再一起確認可行步驟，避免用細節淹沒發想。','Start with a recommendation and its two key reasons, keeping full detail available separately. With a Peacock-like approach, acknowledge the idea’s purpose before checking feasible steps together.']),
 s(['人際關係中的理解','Understanding in relationships'],['指出不一致可能是你表達關心的方式，對方卻可能只感到被糾正。談敏感事情時，先理解感受，再詢問是否一起分析；不是每段對話都要找出最佳方案。','Pointing out inconsistency may be a form of care for you, but can feel like correction to someone else. In a sensitive conversation, understand the feeling before asking whether analysis would help.']),
 s(['一個可實行的練習','One practical exercise'],['為下一次日常決定訂一個資料收集上限，例如只比較三個選項。用事先訂好的標準選擇，並觀察結果是否真的需要更多研究。','Set an information limit for your next everyday decision, such as comparing three options. Choose against criteria agreed beforehand and observe whether further research would really have helped.']),
 ]},
 {path:'/dope/peacock',title:['孔雀型：讓熱情與創意落地','Peacock style: bring enthusiasm and ideas into action'],description:['探索 DOPE 孔雀型的表達、創意及連結優勢，練習聆聽、跟進承諾與跨風格合作。','Explore the Peacock style’s expression, creativity and connection, with practical ways to listen, follow through and collaborate across styles.'],kind:'type',links:['/dope','/dope/owl','/dope/eagle','/guides/communication-differences'],sections:[
 s(['孔雀風格是甚麼？','What is the Peacock style?'],['孔雀代表透過交流、點子和熱情打開可能性的選擇。你可能喜歡讓事情變得有趣，也從大家的反應取得靈感；這不表示你每天都精力充沛。','Peacock represents choices that open possibilities through conversation, ideas and enthusiasm. You may enjoy making an activity engaging and drawing inspiration from people’s reactions. You need not feel energetic every day.']),
 s(['優勢：讓想法容易參與','Strength: making ideas inviting'],['故事、比喻和開放提問能吸引參與，讓原本抽象的目標變得有人情味。團隊停滯時，你可以提出不同角度，協助大家重新看到可能。','Stories, analogies and open questions can invite participation and make an abstract goal feel human. When a group stalls, another angle can help people see a possibility again.']),
 s(['挑戰：點子比跟進快','Challenge: ideas can outpace follow-through'],['新靈感若不斷取代原有承諾，別人會難以知道真正方向。把「正在發想」和「已決定要做」分開，並記下下一步與負責人。','If fresh ideas keep replacing commitments, others may struggle to know the actual direction. Separate brainstorming from decisions and record the next step and its owner.']),
 s(['團隊合作與溝通','Teamwork and communication'],['說完一個想法後停一下，邀請還沒發言的人。和偏貓頭鷹風格的人合作時，補上時間、資源和成功標準，讓創意有可討論的基礎。','Pause after an idea and invite someone who has not spoken. With an Owl-like approach, add timing, resources and success criteria so the idea has a concrete basis for discussion.']),
 s(['人際關係中的投入','Engagement in relationships'],['共同體驗可能是你表達親近的方式。對方需要安靜時，不必立即填補沉默；記住對方以前提過的小事，也是一種深度的關心。','Shared experiences may express closeness for you. When another person needs quiet, you need not fill every silence. Remembering something they mentioned earlier can be a deeper form of attention.']),
 s(['一個可實行的練習','One practical exercise'],['每次提出新計畫，寫下一個十五分鐘內可開始的步驟。下一次見面前先完成它，讓熱情留下看得見的進展。','For each new plan, write one step you can begin within fifteen minutes. Complete it before the next conversation so enthusiasm leaves visible progress.']),
 ]},
 {path:'/dope/eagle',title:['老鷹型：果斷前進，也讓別人跟得上','Eagle style: decisive action that brings others along'],description:['認識 DOPE 老鷹型的目標與行動風格，理解速度的盲點，學習在決策時保留聆聽與信任。','Understand the Eagle style’s goals and action, the blind spots of speed and ways to preserve listening and trust when deciding.'],kind:'type',links:['/dope','/dope/dove','/dope/peacock','/guides/communication-differences'],sections:[
 s(['老鷹風格是甚麼？','What is the Eagle style?'],['老鷹代表直接說明立場、確立目標和推進行動的選擇。你可能希望討論能有結論，並願意承擔決定；這不是領導能力或地位的排名。','Eagle represents choices to state a position, establish a goal and move into action. You may want discussions to reach a conclusion and be willing to own a decision. This is not a ranking of leadership ability or status.']),
 s(['優勢：把注意力放回目標','Strength: returning attention to the goal'],['當選項太多或時間緊迫，你可能能整理優先次序並指出下一步。清楚說明要達成的成果，可以減少大家各自忙碌卻方向不同的情況。','When options multiply or time is short, you may identify priorities and a next step. Clarifying the intended outcome can reduce the chance that everyone stays busy in different directions.']),
 s(['挑戰：快不等於大家都明白','Challenge: speed does not ensure understanding'],['別人沒即時反對，不代表沒有疑慮。重要決定之前，留一段時間問「我們忽略了甚麼？」並說明哪些地方仍可調整。','The absence of immediate objections does not mean there are no concerns. Before an important decision, ask what has been missed and explain which parts remain open to adjustment.']),
 s(['團隊合作與溝通','Teamwork and communication'],['把原因和目標一起說，讓分工不只像命令。和偏鴿子風格的人合作時，主動詢問安排對人的影響，並給對方不受催促的回覆空間。','Explain the reason with the goal so assignments do not feel like commands alone. With a Dove-like approach, ask how the arrangement affects people and allow an unhurried response.']),
 s(['人際關係中的互相尊重','Mutual respect in relationships'],['解決問題可以表達在乎，但對方有權選擇自己的方法。先問他想得到甚麼協助；在沒有共同決策需要時，不必替對方訂下一步。','Problem-solving can show care, but another person is entitled to their own approach. Ask what help they want. Where no shared decision is needed, you need not set their next step.']),
 s(['一個可實行的練習','One practical exercise'],['下一次作決定，先請一位步調不同的人指出一個風險。把回應納入方案或清楚解釋取捨，練習讓果斷也包括聆聽。','Before your next decision, ask someone with a different pace to identify a risk. Incorporate the response or explain the trade-off, practicing decisiveness that includes listening.']),
 ]},
];
export const guides:ContentPage[]=[
 {path:'/guides/read-personality-results',kind:'guide',title:['人格測驗結果怎樣看？從比例到日常觀察','How to read personality test results without boxing yourself in'],description:['用具體例子理解人格測驗的比例、接近分數和重測差異，將結果轉成可觀察的生活問題。','Understand percentages, close scores and changing results, then turn a personality quiz into useful observations from everyday life.'],links:['/tests/personality-16','/personality/infp','/methodology','/guides/dope-vs-16-types'],sections:[
 s(['先看分數代表甚麼','Start with what the number measures'],['Twynzo 的 DOPE 與戀愛測驗每題選一種風格，選了 8 題就是 40%。這只表示 20 題中有 8 次選擇對應該風格，不代表你有 40% 的能力，也不是比 40% 的人更突出。16 型的兩端比例則是原始分數的換算，不能與前兩種直接比較。','In Twynzo’s DOPE and love quizzes, choosing a style eight times gives 40%. That means eight of twenty answers correspond to it, not 40% ability or a rank above 40% of people. The 16-type paired percentages convert a different raw score and cannot be directly compared with these counts.']),
 s(['分數接近時，不急著定型','When scores are close, resist a firm label'],['假如 E / I 是 56% / 44%，一兩題不同選擇就可能改變較高的一端。先找出甚麼場合你想交流、甚麼場合想獨處。若完全同分，網站用 X 保留未明確的面向，讓你繼續比較，而不是任意選一端。','If E / I reads 56% / 44%, changing one or two answers may change the leading side. Look for situations where you want interaction and those where you prefer solitude. Exact ties use X to leave a dimension open rather than selecting a side arbitrarily.']),
 s(['為甚麼重測會不同？','Why might a retake differ?'],['工作壓力、最近經驗、想像的對象以及對題目的理解，都可能影響回答。先保持相近的作答情境，再比較改變的題目；不要只為得到喜歡的標籤而重測。差異可以提示你留意情境，但不能單靠它推斷人格發生重大變化。','Stress, recent experiences, whom you imagine and how you interpret an item can affect answers. Compare under similar conditions and examine which responses changed. Repeating until a preferred label appears offers little insight; a difference alone cannot establish a major personality change.']),
 s(['把結果轉成一週觀察','Turn a result into a week of observation'],['選一個結果提示，例如「我常先分析再回應」。記錄三次真實對話：當時有甚麼選擇、你做了甚麼、結果如何。最後找一個反例。能同時說出符合與不符合之處，比只背類型名稱更有用。','Choose one prompt, such as “I often analyze before responding.” Record three real conversations: the options, your action and the outcome. Then find a counterexample. Being able to describe both fit and mismatch is more useful than memorizing a label.']),
 s(['和朋友分享時可以問甚麼？','What can you ask a friend?'],['可以問：「哪一段像我？哪個場合不一樣？我們下次合作想試甚麼？」不要用結果判斷誰適合被聘用、誰一定適合交往，或替他人解釋所有行為。網站的結果供自我探索，沒有提供這些用途所需的驗證。','Ask which passage fits, where it does not and what you could try in your next shared task. Avoid using a result to decide who should be hired, predict a successful relationship or explain every action. These quizzes have not been validated for those purposes.']),
 ]},
 {path:'/guides/dope-vs-16-types',kind:'guide',title:['DOPE 與 16 型人格有甚麼不同？怎樣選測驗','DOPE vs 16-type personality: which quiz should you choose?'],description:['比較四鳥溝通風格與四組人格偏好的用途、題目和結果，了解為何兩者不能直接換算。','Compare four bird communication styles with four personality preference pairs, and understand why one result cannot be converted into the other.'],links:['/tests','/dope','/tests/personality-16','/personality/istj','/guides/read-personality-results'],sections:[
 s(['兩個測驗在問不同的問題','They ask different questions'],['DOPE 聚焦日常溝通中的相對選擇：先理解人、查資料、打開點子，還是推進目標？16 型探索則把注意力、資訊、判斷與安排分開觀察。前者適合開啟合作對話，後者適合整理不同面向的偏好。','DOPE focuses on relative choices in everyday communication: understand people, check information, open possibilities or advance a goal. The 16-type exploration separates attention, information, judgment and approach to plans. One can start a teamwork conversation; the other organizes reflection across dimensions.']),
 s(['題目與比例如何不同？','How do the items and percentages differ?'],['Twynzo DOPE 有 20 題情境題，各風格比例合計 100%。16 型探索有 24 題，每個面向 6 題，反向題反轉計分；每一對比例合計 100%，四個面向各自獨立。這些比例都不是測驗準確率。','Twynzo DOPE has 20 scenarios, with style shares totaling 100%. The 16-type exploration has 24 items, six per dimension, including reverse scoring. Each pair totals 100%; the four dimensions are separate. Neither kind of percentage is an accuracy score.']),
 s(['不能把鳥類直接換成四字母','A bird cannot be converted into four letters'],['喜歡交流的孔雀輪廓，不代表一定是某個 E 開頭的類型；同一個人也可能在工作和朋友面前採取不同風格。題目、選項和計分方法不同，網站不提供跨測驗的對照診斷。','An expressive Peacock profile does not establish a particular E-leading type. A person may also communicate differently at work and with friends. The questions and scoring differ, so Twynzo does not provide a diagnostic conversion between the frameworks.']),
 s(['按今天的目的選擇','Choose by today’s purpose'],['想和朋友討論「怎樣說話比較容易合作」，先做 DOPE。想整理「我如何取得資訊或安排生活」，可以做 16 型探索。若重點是表達在乎與相處期待，戀愛人格測驗更貼近題目。做一個並仔細反思，也比追求做完所有測驗有用。','Start with DOPE to discuss what makes communication easier. Choose 16-type exploration to reflect on information and daily arrangements. For affection and relationship expectations, the love quiz is closer to the topic. Reflecting carefully on one can be more useful than collecting every result.']),
 s(['概念來源與產品界線','Terminology and product boundaries'],['MBTI 四組偏好的概念可參考 Myers & Briggs Foundation 的介紹。Twynzo 的題目與解讀為原創自我探索內容，並非官方 MBTI® 評估，也未聲稱與其權利人有關聯。DOPE 內容同樣沒有學術效度或專業背書的聲稱。','The Myers & Briggs Foundation explains the four MBTI preference pairs. Twynzo’s questions and interpretations are original reflection content, not the official MBTI® assessment or an affiliated product. Twynzo also makes no claim of academic validation or professional endorsement for its DOPE quiz.']),
 ]},
 {path:'/guides/communication-differences',kind:'guide',title:['溝通風格不同，怎樣把對話接起來？','How to connect across different communication styles'],description:['透過四個具體對話練習，在速度、細節、氣氛與關係需要不同時，找到可共同採取的下一步。','Four practical conversation exercises for differences in pace, detail, atmosphere and relationship needs, with a shared next step.'],links:['/dope','/dope/dove','/dope/owl','/dope/peacock','/dope/eagle','/tests/love-personality','/guides/read-personality-results'],sections:[
 s(['先談需要，再談類型','Name the need before naming a type'],['「你就是老鷹型」容易變成指責。「我需要知道我們何時決定」才是可回應的訊息。即使做過測驗，也先問當下需要，不把類型當成對方一定會怎樣的理由。','“You are such an Eagle” can sound accusatory. “I need to know when we are deciding” gives someone a request they can answer. Even after a quiz, ask about the current need instead of treating a style as an explanation of what someone must do.']),
 s(['速度不同：設兩段時間','Different pace: use two stages'],['一個人想立即定案，另一個人還要整理。試著約定先花十分鐘確認已知資訊，再於指定時間決定。把可逆的小決定與難撤回的大決定分開，不必全部使用同一速度。','One person wants closure while another needs time. Agree to first review known information for ten minutes and then decide at a stated time. Separate reversible choices from hard-to-reverse commitments instead of using one pace for everything.']),
 s(['細節不同：先結論，後依據','Different detail needs: conclusion, then evidence'],['用三句話開始：「我的建議是……」「主要原因是……」「還不確定的是……」。需要更多資料的人可以往下問，想先掌握方向的人也不會迷失在細節裡。','Start with three sentences: “My recommendation is…”; “The main reason is…”; “What remains uncertain is…”. Someone who needs detail can ask further, while someone seeking direction is not lost in the background.']),
 s(['氣氛不同：讓安靜也能參與','Different atmosphere needs: include quiet participation'],['熱烈討論後留一分鐘各自寫想法，再輪流分享。主持人可以說：「先不用回應，我們聽完每個人的一點。」這比只要求安靜的人主動插話更公平。','After an energetic discussion, leave a minute for individual notes and invite each person to share. Try “No responses yet; let us hear one point from everyone.” This offers more access than simply asking quieter people to interrupt.']),
 s(['關係需要不同：確認想要的支持','Different support needs: check before helping'],['對方抱怨時，問：「你想我聽聽，還是一起想方法？」若已發生誤會，可以先說明剛才哪句話造成甚麼影響，再請對方補充他的意思。用具體行為修復，避免把人格當成藉口。','When someone vents, ask whether they want listening or ideas. After a misunderstanding, identify which statement had what impact and invite them to explain their meaning. Repair a specific behavior rather than using personality as an excuse.']),
 ]},
];
const trust:ContentPage[]=[
 {path:'/about',title:['關於 Twynzo：給好奇自己的你','About Twynzo: a place for self-curiosity'],description:['Twynzo 提供免費中英文自我探索測驗，把結果作為對話起點，讓你用自己的步調理解偏好。','Twynzo offers free English and Traditional Chinese self-reflection quizzes, using results as a starting point for conversation.'],links:['/tests','/methodology','/privacy'],sections:[
 s(['為甚麼有這個網站','Why this site exists'],['Twynzo 希望把認識自己的起點變得輕鬆：用生活情境作答，閱讀一段解釋，再想起真實生活中的例子。像素星空和太空人象徵探索，不是對人格的科學宣稱。','Twynzo aims to make a starting point for self-reflection approachable: answer everyday situations, read an interpretation and connect it with examples from your life. The pixel universe and astronaut express exploration, not a scientific claim about personality.']),
 s(['你可以在這裡做甚麼','What you can do here'],['你可以免費完成 DOPE、16 型人格與戀愛人格測驗，切換繁中或英文，儲存結果圖卡並與朋友交流。所有現有測驗不需註冊；Stripe 的 US$3 咖啡贊助是自願的。','You can take DOPE, 16-type and love quizzes for free, switch between English and Traditional Chinese and save a result card to discuss with friends. Current quizzes need no account. The US$3 coffee contribution through Stripe is optional.']),
 s(['內容由誰提供','Who provides the content'],['網站與內容以 Twynzo 名義發布。題目和文章是原創自我探索材料，製作過程使用 AI 輔助撰寫與程式開發；沒有宣稱心理師審核、學術效度或官方測驗機構背書。發現內容不適合你時，保留自己的判斷。','The site and its content are published under the Twynzo name. Original reflection material is created with AI assistance in writing and development. No psychologist review, academic validation or endorsement by an official assessment body is claimed. Keep your own judgment when a passage does not fit.']),
 ]},
 {path:'/methodology',title:['測驗方法與限制：題目、計分和結果','Quiz methodology: questions, scoring and limitations'],description:['了解 Twynzo 三種測驗的題數、計分、同分處理、匿名計數及資料使用方式，不把探索結果當作診斷。','Understand the three Twynzo quizzes, including scoring, ties, anonymous counting and data handling, without treating results as a diagnosis.'],links:['/tests','/guides/read-personality-results','/privacy','/about'],sections:[
 s(['設計目的與原創題目','Purpose and original questions'],['題目以日常情境與自我描述引導反思，沒有正確答案。每題要求相對選擇，因此不會涵蓋一個人的全部行為。這些原創題庫並未完成代表性抽樣、信度或效度驗證，也沒有適用於診斷、招聘或配對的證據。','Everyday situations and self-descriptions invite reflection without right answers. Each item asks for a relative choice and cannot cover all of a person’s behavior. These original item sets have not undergone representative sampling or reliability and validity studies and have no established diagnostic, hiring or matching use.']),
 s(['DOPE 與戀愛人格：每個選項一分','DOPE and love personality: one point per choice'],['兩者各有 20 題。每個選項對應一種風格，每次選擇加一分；比例為該風格次數除以 20，乘以 100。最高分並列時呈現混合風格，不任意打破同分。戀愛測驗的四種風格是暖心表達、專注陪伴、踏實照顧和共同成長，並非依附類型。','Both have 20 questions. Each choice adds one point to a style; its share is the selection count divided by 20, multiplied by 100. Tied leaders remain a blend. The love styles describe warm expression, present companionship, practical care and shared growth, not attachment classifications.']),
 s(['16 型人格：四個面向各自計算','16-type personality: four separate dimensions'],['24 題分成 E/I、S/N、T/F、J/P 四組，每組 6 題。四級回答依序給 +3、+1、−1、−3，反向題將正負反轉。每組總分範圍為 −18 至 +18；左端比例為 (總分 + 18) ÷ 36 × 100 後四捨五入，右端為 100 減左端。總分為零以 X 顯示並保留可能組合。','The 24 items form four six-item dimensions: E/I, S/N, T/F and J/P. Four responses score +3, +1, −1 or −3; reverse items invert the sign. Each sum ranges from −18 to +18. The left percentage is rounded from (sum + 18) / 36 × 100; the right is its complement. A zero sum displays X and preserves possible combinations.']),
 s(['結果可以與不可以說明甚麼','What a result can and cannot tell you'],['比例描述本次作答，不是人口百分位、準確率或能力等級。四字母與鳥類名稱是解讀用語，不會預測職業成就或關係成功。不同情境和題目理解會影響結果。16 型內容以 MBTI 概念為靈感，但不是官方 MBTI® 評估，亦無關聯聲稱。','Percentages describe these answers, not population percentiles, accuracy or ability. Letter codes and birds are interpretive language, not predictions of career or relationship success. Context and item interpretation can change results. The 16-type product is inspired by MBTI concepts but is not the official MBTI® assessment or an affiliated product.']),
 s(['匿名完成計數','Anonymous completion counting'],['每個測驗的顯示數字由 3,125 初始基數加上記錄到的新增完成組成；初始基數並非經驗證的實際受測者。新增完成以匿名瀏覽器識別碼在每個測驗去重，同一瀏覽器重測通常不重複增加。不同裝置、清除 Cookie 或到期後可能再計，因此不是獨立真人數。','Each displayed quiz count consists of an initial baseline of 3,125 plus recorded completions. The baseline is not a verified count of actual participants. New completions are deduplicated per quiz by an anonymous browser identifier. Different devices, cleared cookies or expiry can lead to another count, so the total is not a count of distinct people.']),
 s(['答案與分享','Answers and sharing'],['計分在瀏覽器進行。完成時答案會傳到本站 API 作格式驗證，但不存進測驗資料庫；資料庫保存去重用雜湊及完成時間。切換語言時用工作階段儲存暫存答案，只有 60 秒內的資料會被接收。結果圖卡在裝置產生；是否分享由你決定。','Scoring happens in the browser. On completion, answers are sent to the site API for format validation but are not stored in the quiz database; it keeps a deduplication hash and completion time. Language switching uses session storage, accepting transferred answers only within 60 seconds. Result cards are generated on your device and you choose whether to share them.']),
 ]},
 {path:'/privacy',title:['隱私說明：測驗資料與 Cookie','Privacy: quiz data and cookies'],description:['說明 Twynzo 的答案處理、匿名完成計數、語言暫存、Stripe 贊助及外部分享。','How Twynzo handles answers, anonymous completion counts, language transfers, Stripe contributions and external sharing.'],links:['/methodology','/terms','/about'],sections:[
 s(['這份說明的範圍','Scope of this notice'],['本頁說明目前 Twynzo 測驗的資料流程，不宣稱第三方服務不會處理任何資料。現有測驗不要求姓名、電郵或帳戶，也沒有新增 Google Analytics 或廣告追蹤器。網站託管服務仍可能處理請求、IP 位址和技術日誌以提供與保護服務。','This notice describes the current Twynzo quiz data flow, not a claim that third-party services process no data. Current quizzes request no name, email or account, and no Google Analytics or advertising tracker has been added. Hosting services may still process requests, IP addresses and technical logs to deliver and protect the service.']),
 s(['答案及暫存','Answers and temporary storage'],['答案主要留在瀏覽器記憶體，重新載入通常會清除進度。切換語言使用 sessionStorage，轉移資料讀取後刪除，只接收 60 秒內的內容；未完成跳轉的暫存可留到工作階段結束。完成時答案送到 API 驗證格式，不寫入測驗資料庫；不應把免費工具視作保密醫療服務。','Answers mainly stay in browser memory; reloading normally clears progress. Language switching uses sessionStorage, removing transferred data after reading and accepting it only within 60 seconds. An unused transfer may remain until the session ends. Completion sends answers to the API for format validation, not quiz-database storage. This free tool is not a confidential medical service.']),
 s(['Cookie 與去重資料','Cookie and deduplication data'],['dope_visitor_v1 是簽署的匿名瀏覽器識別 Cookie，有效期約一年，用於防止同一瀏覽器重複增加完成次數。資料庫保存衍生雜湊、測驗識別及完成時間，不保存姓名或作答內容。目前沒有自動清除歷史完成紀錄的排程。清除網站資料可刪除裝置上的 Cookie 與暫存，但不會自動刪除已記錄的雜湊。','The signed dope_visitor_v1 cookie identifies an anonymous browser for about a year to avoid repeated completion increments. The database retains a derived hash, quiz identifier and completion time, not a name or answers. There is currently no scheduled deletion of historical completion records. Clearing site data removes local cookies and storage but does not automatically delete an already-recorded hash.']),
 s(['服務供應商、贊助與分享','Providers, contributions and sharing'],['網站由 Vercel 託管，計數使用 Supabase。咖啡贊助會前往 Stripe；請在付款前閱讀其隱私及付款資訊，Twynzo 不收取你的完整卡號。分享圖卡或結果文字到其他平台後，該平台會依自己的規則處理內容。','Vercel hosts the website and Supabase supports counting. Coffee contributions open Stripe; review its privacy and payment information before paying. Twynzo does not collect your full card number. Once you share a card or result text elsewhere, the receiving platform handles it under its own rules.']),
 ]},
 {path:'/terms',title:['使用說明與條款','Terms of use'],description:['Twynzo 免費測驗的使用範圍、結果限制、分享及自願贊助說明。','The scope of Twynzo’s free quizzes, result limitations, sharing and optional contributions.'],links:['/privacy','/methodology','/about'],sections:[
 s(['適用範圍','Scope'],['Twynzo 提供免費自我探索內容與測驗。你可用於個人反思和一般交流；不要把結果當作醫療診斷、專業評估、招聘篩選或關係配對保證。這份說明不排除適用法律賦予且不可放棄的權利。','Twynzo provides free self-reflection content and quizzes for personal exploration and ordinary discussion. Do not treat results as a medical diagnosis, professional assessment, hiring screen or relationship guarantee. This notice does not exclude non-waivable rights under applicable law.']),
 s(['原創內容與分享','Original content and sharing'],['你可以分享自己的結果圖卡與網站連結。引用文章時請保留 Twynzo 出處，不要把內容包裝成官方 MBTI 評估或經驗證的心理工具。第三方名稱與商標屬各自權利人。','You may share your own result cards and links to the site. Attribute Twynzo when quoting an article and do not present the material as an official MBTI assessment or a validated psychological tool. Third-party names and marks belong to their respective rights holders.']),
 s(['自願贊助','Optional contributions'],['Stripe 咖啡連結的 US$3 為自願支持，現有測驗結果不以付款為條件，也不因付款而更準確。付款前請確認 Stripe 頁面的金額與交易資訊；本網站不承諾目前不存在的付費產品或服務。','The US$3 Stripe coffee link is optional support. Current quiz results do not require payment and do not become more accurate after paying. Confirm the amount and transaction information on Stripe; this site promises no premium product or service that does not currently exist.']),
 s(['服務與內容的限制','Service and content limitations'],['網站可能維護、修改內容或暫時無法使用。結果僅反映當次回答，文章中的傾向是思考提示，不保證符合每個人。請尊重他人，不以測驗標籤作羞辱、排斥或替他人作重要決定的依據。','The site may be maintained, updated or temporarily unavailable. Results reflect the answers given, and tendencies in articles are reflection prompts rather than descriptions guaranteed to fit everyone. Respect others and avoid using labels to shame, exclude or make consequential decisions for them.']),
 ]},
];
export const contentPages:ContentPage[]=[
 ...typeProfiles.map(p=>({path:'/personality/'+p.code.toLowerCase(),title:[`${p.code} 人格探索：${p.name[0]}`,`${p.code} personality reflection: ${p.name[1]}`] as TextPair,description:[`從日常例子認識 ${p.code} 的思考、溝通與相處傾向，探索優勢、盲點和成長練習。原創自我探索解讀，不是職業或配對預測。`,`Explore ${p.code} through everyday communication, relationships and work, with strengths, blind spots and a practical growth exercise.`] as TextPair,kind:'type' as const,sections:[...p.sections.map((body,i)=>s(typeHeadings[i],body)),...typeContexts[p.code].map((body,i)=>s(contextHeadings[i],body))],links:['/tests/personality-16','/guides/read-personality-results',...(p.code==='INFP'?['/guides/infp-love']:[]),...p.related.map(code=>'/personality/'+code.toLowerCase())]})),
 ...dopeProfiles.map(p=>({...p,sections:[...p.sections,...dopeContexts[p.path]]})),...guides,...relationshipGuides,...trust,
 {path:'/tests',kind:'hub',title:['人格測驗總覽：選擇今天想探索的主題','Personality test collection: choose your next exploration'],description:['比較 Twynzo 的免費 DOPE、16 型人格和戀愛人格測驗，按溝通習慣、日常偏好或關係期待選擇。','Compare Twynzo’s free DOPE, 16-type and love quizzes by communication habits, everyday preferences and relationship expectations.'],links:['/dope','/tests/personality-16','/tests/love-personality','/guides/dope-vs-16-types','/methodology'],sections:[
 s(['想理解怎樣合作？選 DOPE','For communication and teamwork: DOPE'],['20 題、約 4 分鐘。以鴿子、貓頭鷹、孔雀和老鷹描述本次選擇中的溝通風格，適合與朋友討論怎樣聆聽、給回饋和作決定。','20 questions, about four minutes. Dove, Owl, Peacock and Eagle describe communication choices in these answers, offering a starting point for discussing listening, feedback and decisions.']),
 s(['想整理日常偏好？選 16 型探索','For everyday preferences: 16-type exploration'],['24 題、約 4–5 分鐘。分別觀察注意力、資訊、判斷與安排四個面向，保留同分和接近的偏好。這是 MBTI 概念靈感的原創內容，不是官方評估。','24 questions, about four to five minutes. Explore attention, information, judgment and planning separately, with room for close or tied preferences. Original MBTI-inspired content, not the official assessment.']),
 s(['想談表達在乎？選戀愛人格','For affection and expectations: love personality'],['20 題、約 4–5 分鐘。從表達、陪伴、照顧與成長四種方式認識相處偏好，單身或有伴都可以回答。結果不是依附診斷，也不提供最佳配對排行。','20 questions, about four to five minutes. Explore expression, companionship, practical care and growth whether single or partnered. Results are not an attachment diagnosis or a ranking of compatible partners.']),
 s(['免費結果，依自己的步調','Free results at your own pace'],['所有測驗支援中英文，免費查看結果、實用建議及下載圖卡，不需註冊。選平常的反應，不必選看起來最理想的答案；測驗後可以用指南把結果連回真實生活。','All quizzes offer English and Traditional Chinese, free results, practical prompts and downloadable cards without registration. Choose your usual response rather than the most ideal-looking answer, then use a guide to connect the result with real life.']),
 ]},
 {path:'/personality',kind:'hub',title:['16 型人格閱讀地圖：從四字母回到日常','The 16-type reading map: from letters to everyday life'],description:['選擇一個人格輪廓，閱讀溝通、關係、工作環境及成長練習，也比較不完全符合自己的部分。','Choose a profile to explore communication, relationships, work environments and growth, including the parts that do not fit you.'],links:['/tests/personality-16',...typeProfiles.map(p=>'/personality/'+p.code.toLowerCase()),'/guides/read-personality-results'],sections:[s(['怎樣使用類型文章','How to use these profiles'],['以下 16 篇提供不同偏好組合的原創反思角度，不是 16 種固定人類。閱讀你的結果後，也選一個相近類型比較；找出生活例子與反例，不把文章當作能力、職業或配對規則。','These sixteen original profiles offer perspectives on preference combinations, not sixteen fixed kinds of people. Read your result and compare a neighboring type. Look for examples and counterexamples rather than rules about ability, careers or compatibility.'])]},
 {path:'/guides',kind:'hub',title:['自我探索指南：讓測驗之後的對話更有用','Self-discovery guides: make the conversation after a quiz useful'],description:['閱讀人格結果、比較 DOPE 與 16 型探索，以及練習不同溝通風格之間的合作。','Read personality results, compare DOPE with 16-type exploration and practice cooperation across communication styles.'],links:[...guides,...relationshipGuides].map(g=>g.path),sections:[s(['從問題開始閱讀','Start with a question'],['不確定百分比代表甚麼？先讀結果解讀。還沒選好測驗？比較兩種框架。已想起一段真實對話？試試溝通練習。這些指南提供可執行的小步驟，不以人格標籤取代你的判斷。','Unsure what percentages mean? Start with interpreting results. Still choosing a quiz? Compare the frameworks. Have a real conversation in mind? Try the communication exercises. These guides offer practical small steps without replacing your judgment with a label.'])]},
];
export const findContent=(path:string)=>contentPages.find(p=>p.path===path);
