import type {ContentPage} from './editorial';

export const practicalGuides:ContentPage[]=[
 {path:'/guides/personality-preferences',kind:'guide',
 title:['MBTI 字母意思：四組偏好與日常觀察練習','MBTI letters explained: four pairs and a reflection sheet'],
 description:['E/I、S/N、T/F、J/P 分別代表甚麼？用四組偏好對照、一個共同情境及七天觀察表，理解字母與 Twynzo 分數的差別。','Understand E/I, S/N, T/F and J/P with a comparison table, an everyday example and a seven-day worksheet. Learn what Twynzo percentages actually mean.'],
 links:['/tests/personality-16','/personality','/guides/read-personality-results','/guides/dope-vs-16-types','/methodology'],
 sources:[{url:'https://www.myersbriggs.org/my-mbti-personality-type/the-mbti-preferences/',label:['Myers & Briggs Foundation：四組偏好的概念來源','Myers & Briggs Foundation: the four preference pairs']}],
 sections:[
 {heading:['四個字母是在比較甚麼？','What do the four letters compare?'],body:['MBTI 的四字母分別取自四組偏好：E/I 是注意力方向、S/N 是接收資訊、T/F 是作判斷、J/P 是面對外在生活的安排方式。偏好不等於能力，也不是把人分成好壞。下面的簡表介紹概念；生活例子和觀察表是 Twynzo 的原創反思練習，並不是官方 MBTI® 評估。','Each MBTI letter comes from a preference pair: E/I concerns attention, S/N information, T/F judgment, and J/P the approach to the outer world. A preference is not an ability or a ranking. The table introduces these concepts; the everyday example and observation sheet are original Twynzo exercises, not the official MBTI® assessment.'],table:{caption:['四組偏好速查','Four preference pairs at a glance'],headers:[['面向','Dimension'],['兩端的意思','Meaning of each side'],['不要直接推論','Do not assume']],rows:[[['E / I','E / I'],['E 外向：偏向外在互動；I 內向：偏向內在反思。','Extraversion: outward interaction. Introversion: inward reflection.'],['不是社交技巧高低。','Not a measure of social skill.']],[['S / N','S / N'],['S 實感：留意具體資訊；N 直覺：留意連結與可能。','Sensing: concrete information. Intuition: patterns and possibilities.'],['不是有沒有想像力。','Not whether you have imagination.']],[['T / F','T / F'],['T 思考：考慮邏輯準則；F 情感：考慮價值與對人的影響。','Thinking: logical criteria. Feeling: values and effects on people.'],['不是理性對上不理性。','Not rational versus irrational.']],[['J / P','J / P'],['J 判斷：傾向定案和安排；P 感知：傾向保持選擇和調整。','Judging: closure and structure. Perceiving: openness and adjustment.'],['不是勤奮對上懶惰。','Not hardworking versus lazy.']]]}},
 {heading:['同一件事，可以看見不同偏好','Use one situation to notice different preferences'],body:['想像朋友請你一起安排週末聚餐。以下不是用行為反推人格的規則，而是讓你比較「第一個自然想到的需要」。你可能在不同階段使用兩端，也可能只是因為預算、疲倦或過往經驗而改變做法。','Imagine planning a weekend meal with friends. The prompts below compare the need you notice first; they are not rules for diagnosing a type from behavior. You might use both sides at different stages, or change your approach because of cost, tiredness or previous experience.'],items:[['注意力：你想先聊一聊形成想法，還是先自己整理再回覆？兩種方式都可以有積極參與。','Attention: would talking help you form an idea, or would you rather reflect before replying? Either can be active participation.'],['資訊：你先問餐廳價錢、時間和交通，還是先想聚餐可以有甚麼主題？最後仍需兩類資訊。','Information: do you first check price, time and transport, or imagine a theme for the gathering? The plan eventually needs both.'],['判斷：你先用一致的條件比較選項，還是先了解各人的在意之處？公平與照顧可以同時存在。','Judgment: do you first compare options against consistent criteria, or ask what matters to each person? Fairness and care can coexist.'],['安排：你希望提早訂位，還是多留一點時間看大家的反應？一起約定截止時間可以減少誤會。','Planning: would you prefer to book early, or keep options open while people respond? Agreeing on a deadline can reduce misunderstanding.']]},
 {heading:['七天觀察表：先收集例子，再看標籤','A seven-day sheet: collect examples before labels'],body:['每天選一個小決定，花兩分鐘記下情境和實際做法。不必每天填四個面向，也不要只記符合測驗結果的例子。七天後看看哪些需要重複出現、哪些受到環境限制；如果資料仍然混合，就保留不確定。表格可複製到自己的筆記，網站不收集這些記錄。','Choose one small decision each day and spend two minutes recording its context and your actual response. You do not need all four dimensions every day. Include examples that contradict your result. After seven days, look for recurring needs and environmental constraints. If the evidence stays mixed, keep that uncertainty. Copy this sheet to your own notes; the website does not collect these observations.'],worksheet:['日期與情境：\n我最先留意的需要：\n我實際做了甚麼：\n有沒有時間、角色或他人要求的限制：\n一個不符合目前標籤的例子：\n下次想嘗試的小改變：','Date and situation:\nThe need I noticed first:\nWhat I actually did:\nConstraints from time, role or other people:\nOne example that does not fit my current label:\nOne small change to try:']},
 {heading:['Twynzo 的百分比不是官方 MBTI 分數','Twynzo percentages are not official MBTI scores'],body:['Twynzo 使用 24 道原創題目，每組偏好各六題。百分比由本次答案的加權分數換算，不是人口百分位、準確率或「有多像某類型」。同分時顯示 X；例如 INXP 表示 T/F 這組沒有偏向一端。先比較兩端的生活例子，比強行選一個字母更有用。完整公式與反向題處理見測驗方法頁。','Twynzo uses 24 original questions, six per pair. Percentages convert weighted answers from this attempt; they are not population percentiles, accuracy estimates or a measure of how much you belong to a type. A tie displays X: INXP means the T/F dimension did not favor either side. Compare real examples on both sides before choosing a label. The methodology page explains the formula and reverse-scored items.']},
 {heading:['從解讀走到一個小實驗','Turn the interpretation into one small experiment'],body:['選一個最近卡住的情境，只改變一次對話方式。例如習慣立即討論時，先給對方三分鐘整理；習慣保留選項時，主動說明何時會定案。事後問「這次清楚了甚麼？」而不是「我變成另一型了嗎？」如果測驗文字與你的經驗不符，可以不用它。','Choose one recent difficulty and change one part of the conversation. If you usually discuss immediately, offer the other person three minutes to gather thoughts. If you keep options open, say when you will decide. Afterwards ask what became clearer, rather than whether you became a different type. If the quiz language does not fit your experience, you can leave it aside.']}
 ]},
 {path:'/guides/dope-team-exercise',kind:'guide',
 title:['DOPE 團隊活動：15 分鐘溝通練習與交接範本','DOPE team activity: a 15-minute communication exercise'],
 description:['不用替同事貼標籤：透過自願分享、四種溝通需要和一份交接範本，把 DOPE 測驗變成 15 分鐘團隊討論。','Turn DOPE into a voluntary 15-minute team conversation. Use four communication needs, a facilitator agenda and a concrete task-handover template.'],
 links:['/dope','/dope/dove','/dope/owl','/dope/peacock','/dope/eagle','/guides/communication-differences','/methodology'],
 sections:[
 {heading:['活動目標：改進一次交接','The goal: improve one handover'],body:['這個 DOPE 團隊活動用四種溝通需要檢查一項共同任務：人是否被理解、細節是否清楚、想法是否被聽見、下一步是否確定。它是 Twynzo 原創討論練習，不是人事評估。適合二至四人自願參與；人數較多可分組。測驗可以事前自由完成，也可以完全不做，只使用以下提示。','This DOPE team activity checks four communication needs around one shared task: understanding people, clarifying detail, hearing ideas and deciding a next step. It is an original Twynzo discussion exercise, not an employment assessment. Use it with two to four willing participants, or split a larger group. Taking the quiz beforehand is optional; the prompts work without scores.']},
 {heading:['15 分鐘主持流程','The 15-minute facilitator agenda'],body:['準備一張紙和一個真實但低壓的任務，例如交接下週例會。主持人先說：「今天只改善一件事，不替任何人判定鳥型。可以略過問題，不必公開分數。」計時只是分配發言空間；尚未完成的議題可以另約時間。','Bring a sheet of paper and one real, low-pressure task, such as handing over next week’s meeting. Open with: “We are improving one task, not assigning birds to people. You may skip a question and keep scores private.” The timer shares speaking space; unfinished issues can get a separate conversation.'],ordered:true,items:[['0–2 分鐘：確認任務、完成期限，以及大家願意參與。每人說一句希望這次改善甚麼。','Minutes 0–2: confirm the task, deadline and willingness to participate. Each person names one hoped-for improvement.'],['2–5 分鐘：安靜寫下自己最需要的一項資訊，和最容易被忽略的一項需要。','Minutes 2–5: privately note the information you most need and one need that is often overlooked.'],['5–9 分鐘：輪流各說一分鐘。下一位先簡短重述聽到的需要，再分享自己的；先不辯論。','Minutes 5–9: take one minute each. The next speaker briefly reflects the need they heard before adding their own; postpone debate.'],['9–13 分鐘：用下面的四個檢查角度修改交接訊息，確認缺少的資訊。','Minutes 9–13: use the four checks below to revise the handover and identify missing information.'],['13–15 分鐘：選一個改變、負責人和回顧時間。每人確認是否做得到。','Minutes 13–15: choose one change, an owner and a review time. Each person confirms whether the agreement is workable.']]},
 {heading:['四種鳥，是四個檢查角度','Four birds, four checks'],body:['任何人都可以提出任何一類問題，不必由「最高分的人」負責。若小組都得到相近結果，仍把四項逐一讀過；沒有某種鳥型，不代表團隊缺少能力。','Anyone can ask any of these questions; do not assign them to the highest scorer. Even if everyone has a similar result, read all four checks. An absent bird label does not mean the team lacks an ability.'],items:[['鴿子：誰會受到影響？有沒有誰還沒機會表達困難？','Dove: who is affected, and who has not had a chance to name a difficulty?'],['貓頭鷹：資料在哪裡？完成標準是甚麼？哪些仍未確認？','Owl: where is the information, what counts as done, and what is still unconfirmed?'],['孔雀：有沒有另一個做法？怎樣讓大家容易提出想法？','Peacock: is there another approach, and how can people contribute ideas easily?'],['老鷹：下一步由誰做、何時完成？遇到阻礙時找誰決定？','Eagle: who takes the next step, by when, and who decides when there is a blocker?']]},
 {heading:['把模糊交接改成可回應的訊息','Make a vague handover answerable'],body:['原句：「你幫我處理一下會議吧。」改寫：「請你在星期三中午前整理星期五會議議程，沿用共用資料夾的範本。先詢問每人一項想討論的問題，保留十分鐘開放討論。完成後傳給我確認；若有未收到的資料，在星期二下午告訴我，我們再調整範圍。」這個範例同時給出參與方式、細節、空間和決策點，但仍需對方確認是否可行。','Before: “Can you handle the meeting?” After: “Please draft Friday’s agenda by Wednesday noon using the shared-folder template. Ask everyone for one discussion topic and reserve ten minutes for open discussion. Send the draft to me for review. If information is missing, tell me on Tuesday afternoon so we can adjust the scope.” The example includes participation, details, room for ideas and a decision point. The recipient still needs to confirm that it is feasible.']},
 {heading:['可複製的團隊約定','A team agreement to copy'],body:['不要把所有問題變成一次大改革。填好一份最小約定，下次交接時試用；回顧時比較訊息有沒有更清楚，而不是比較哪種性格表現較好。只記錄工作約定，避免替同事建立人格檔案。','Keep the agreement small enough to try at the next handover. Review whether the message became clearer, rather than which personality performed better. Record the work agreement, not a personality file about colleagues.'],worksheet:['共同任務：\n完成標準與期限：\n需要先確認的人或資料：\n可以自行調整的部分：\n遇到阻礙時的回報方式：\n下一步與負責人：\n回顧時間與一個觀察問題：','Shared task:\nDefinition of done and deadline:\nPeople or information to check first:\nWhat can be adjusted independently:\nHow to report a blocker:\nNext step and owner:\nReview time and one observation question:']},
 {heading:['如果討論卡住','If the discussion stalls'],body:['有人不想分享時，可以只討論任務需要；不要要求公開測驗結果。意見衝突時，先區分事實缺口和需要不同：前者安排查證，後者各提一個可接受的做法。若分歧涉及權限、工作量或資源，交由正常管理流程處理，不把責任推給鳥型。','If someone does not want to share, discuss task requirements without quiz results. When views conflict, separate missing facts from different needs: arrange a fact check for the first, and ask for one acceptable option from each person for the second. Disputes about authority, workload or resources belong in the normal management process, not in bird labels.']}
 ]},
 {path:'/guides/relationship-check-in',kind:'guide',
 title:['情侶溝通問題：10 分鐘定期對話與約定範本','Relationship check-in: questions for a 10-minute talk'],
 description:['從一件感謝、一次需要到一個小約定，用 10 分鐘情侶對話流程和可複製問題，把戀愛人格結果帶回生活。','Use a 10-minute relationship check-in to share appreciation, explain one need and agree on a small action. Includes questions and a reusable template.'],
 links:['/tests/love-personality','/guides/expressing-relationship-needs','/guides/infp-love','/guides/communication-differences','/methodology'],
 sections:[
 {heading:['定期對話要問甚麼？','What should a relationship check-in ask?'],body:['一次簡短的情侶定期對話，可以圍繞三個問題：這週哪件事讓你感到被照顧？哪個時刻你需要不同的支持？接下來願意一起試甚麼小改變？下面是 Twynzo 原創的十分鐘對話流程，不需要測驗分數，也不是關係治療或配對評估。先確認兩人都願意聊，並有不受打擾的時間。','A short relationship check-in can use three questions: what helped you feel cared for this week, when did you need different support, and what small change would you like to try together? The ten-minute agenda below is an original Twynzo conversation exercise. It needs no quiz scores and is not relationship therapy or a compatibility assessment. First check that both people want to talk and have uninterrupted time.']},
 {heading:['十分鐘流程：兩個人都要有空間','A ten-minute agenda with room for both people'],body:['約好一個兩人都方便的時段。若正在趕時間或爭吵，可以改約；不要用計時器強迫對方立刻給答案。每次只處理一個具體的小主題，比把過往所有問題放進同一次對話容易完成。','Choose a time that works for both of you. Reschedule if you are rushing or arguing; do not use the timer to demand an immediate answer. One concrete, manageable topic is easier to complete than bringing every past concern into a single talk.'],ordered:true,items:[['0–2 分鐘：各說一件具體感謝。描述行為，例如「你昨天先問我想不想聊天」，而不只是「你很好」。','Minutes 0–2: each name a specific appreciation. Describe an action, such as being asked whether you wanted to talk, rather than only “You are great.”'],['2–6 分鐘：各用兩分鐘說一個時刻、一種感受和一項需要。另一人先聽完，不搶著解釋動機。','Minutes 2–6: take two minutes each for one moment, a feeling and a need. The listener lets the speaker finish before explaining intentions.'],['6–8 分鐘：重述對方的重點，問「我理解得對嗎？」再比較兩人的請求有沒有衝突。','Minutes 6–8: reflect the main point and ask whether you understood correctly. Then check whether your requests conflict.'],['8–10 分鐘：一起選一個可做到的小行動和回顧時間。可以拒絕或提出替代方案。','Minutes 8–10: choose one feasible action and a time to revisit it. Either person can decline or suggest an alternative.']]},
 {heading:['把問題問得更容易回答','Questions that are easier to answer'],body:['不用一次問完。從下面選一題，讓回答包含真實情境；如果對方不知道，也可以下次再說。測驗顯示的偏好可以提供題目，但不能替對方回答。','Choose one question rather than asking all of them. Invite an example from real life, and allow “I do not know yet.” Quiz preferences can suggest a question, but they cannot answer on another person’s behalf.'],items:[['「這週哪個小動作，讓你感到我有在聽？」','“Which small action this week helped you feel heard?”'],['「你累的時候，想要我陪著、幫忙做事，還是先留一點空間？」','“When you are tired, would company, practical help or some space feel useful?”'],['「有哪個約定我們理解得不一樣？可以各說一次原本的想法嗎？」','“Which agreement did we understand differently? Can we each describe what we expected?”'],['「下週只改一件小事，你會選甚麼？我做不到時，有甚麼替代方式？」','“If we changed one small thing next week, what would you choose? What is an alternative if I cannot do it?”']]},
 {heading:['範例：下班後的十分鐘','Example: the first ten minutes after work'],body:['甲說：「你回家直接看手機時，我不知道你是不是不想理我。我希望先打個招呼。」乙說：「我想先安靜一下，但不是不想見你。」先不要判定誰更在乎。可以試一個約定：「回家先打招呼，說明想安靜十分鐘；之後一起喝水聊一下。如果今晚特別累，先說明並另約時間。」兩天後回顧，而不是把這個做法變成不能改的規則。','One person says, “When you go straight to your phone, I cannot tell whether you want to talk. I would like a greeting.” The other says, “I need some quiet first; it does not mean I do not want to see you.” Instead of ranking who cares more, try a greeting followed by ten minutes of quiet and a short chat afterwards. If either person is unusually tired, say so and agree another time. Revisit the plan after two days rather than making it an unchangeable rule.']},
 {heading:['可複製的每週對話筆記','A weekly conversation note to copy'],body:['把筆記存到自己選擇的地方；這個網頁不儲存筆記。只保留雙方同意記下的內容，也不必留下分數或私密細節。重點是下次知道要回顧哪個行動，而不是證明誰上次說過甚麼。','Keep the note wherever you choose; this page does not store it. Write down only what both people agree to record, without scores or private details. Its purpose is to remember the action to revisit, not to prove who said what.'],worksheet:['日期：\n我感謝的一件具體事情：\n我想被理解的一個時刻：\n對方重述後，我想補充的地方：\n我們願意試的一個小行動：\n做不到時的替代方案：\n何時回顧，觀察甚麼：','Date:\nOne specific thing I appreciate:\nOne moment I want understood:\nWhat I want to clarify after being heard:\nOne small action we both want to try:\nAn alternative if it is not workable:\nWhen we will revisit it and what we will notice:']},
 {heading:['甚麼時候先停下來？','When should you pause?'],body:['任何一方都可以略過問題或停止。若開始互相指責，先說明需要暫停，再確認是否及何時回到話題。若分享會令你害怕被威脅或報復，不要勉強用這個練習；優先考慮自己的安全及可信任的支持。人格測驗不會判定一段關係是否安全，也不能代替需要時的專業協助。','Either person can skip a question or stop. If the talk turns into accusations, name the need for a pause and check whether and when you want to return. Do not force this exercise if sharing makes you fear threats or retaliation; prioritize your safety and trusted support. A personality quiz cannot determine whether a relationship is safe or replace professional help when needed.']}
 ]}
];
