type Pair = [string,string];
type Question = {q:Pair;a:Pair[]};
export const birds = [
{code:'D',name:['鴿子','Dove'],label:['溫暖的協調者','The caring harmonizer'],desc:['同理、耐心、重視關係','Empathetic, patient, people-focused'],color:'#43886b',tint:'#dfebe1',advice:['你擅長聆聽與建立信任。關心別人之餘，也試著清楚說出自己的需求與界線。與果斷的人溝通時，先提出建議，再解釋對人的影響。','You listen well and build trust. State your own needs and boundaries too. With decisive people, lead with your recommendation, then explain its impact on people.']},
{code:'O',name:['貓頭鷹','Owl'],label:['細膩的思考者','The thoughtful analyst'],desc:['理性、精準、重視細節','Analytical, precise, detail-aware'],color:'#537c9b',tint:'#e0e9ed',advice:['你善於分析與釐清細節。分享資訊時，先說重點，再提供依據。當資料無法完全齊備，設定合理的決策期限，讓討論能夠前進。','You analyze carefully and clarify details. Start with the main point, then offer evidence. When complete information is unavailable, set a reasonable decision deadline.']},
{code:'P',name:['孔雀','Peacock'],label:['熱情的創意家','The expressive enthusiast'],desc:['樂觀、活潑、喜歡交流','Expressive, optimistic, imaginative'],color:'#a4783b',tint:'#eee5d0',advice:['你能用熱情與故事感染他人。記得留空間讓較安靜的人發言，並把新點子整理成清楚的下一步。與重視細節的人合作時，補上具體資訊。','Your energy and stories engage people. Make space for quieter voices and turn ideas into clear next steps. With detail-focused people, add concrete information.']},
{code:'E',name:['老鷹','Eagle'],label:['果斷的行動派','The decisive driver'],desc:['直接、自主、目標導向','Direct, independent, goal-focused'],color:'#997267',tint:'#eee1d9',advice:['你擅長訂方向並推動行動。在快速決定前，邀請不同意見，也確認大家的感受。把目標與原因一起說明，能讓合作更順暢。','You set direction and move things forward. Invite different views and check how others feel before deciding. Explain the reason behind the goal to make collaboration smoother.']}
];
export const questions:Question[] = [
{q:['團隊要展開一個新計畫，你通常會先⋯⋯','When your team starts a new project, you usually…'],a:[['了解大家的想法，確保每個人都被聽見','Listen to everyone and make sure each voice is heard'],['整理資料，釐清細節與可能的風險','Gather information, clarify details and assess risks'],['提出有趣的點子，讓大家期待這次合作','Offer exciting ideas and get everyone enthusiastic'],['訂下目標，分配工作並開始行動','Set a goal, assign tasks and get things moving']]},
{q:['朋友和你的意見不同時，你傾向⋯⋯','When a friend disagrees with you, you tend to…'],a:[['先理解對方的感受','Understand how they feel first'],['仔細比較雙方的理由','Compare the reasoning on both sides'],['用輕鬆的方式打開話題','Keep the conversation light and open'],['直接說明立場，找出結論','State your view directly and seek a conclusion']]},
{q:['安排週末旅行時，你最在意⋯⋯','When planning a weekend trip, you care most about…'],a:[['同行的人都覺得自在','Everyone feeling comfortable'],['交通、時間與住宿安排妥當','Transport, timing and accommodation being well planned'],['有新鮮好玩的體驗','Having fresh, exciting experiences'],['有效率地去到最想去的地方','Efficiently reaching the places you most want to see']]},
{q:['同事向你求助，你的第一個反應是⋯⋯','When a colleague asks for help, your first response is to…'],a:[['耐心聽完，給予支持','Listen patiently and offer support'],['詢問細節，找出問題根源','Ask for details and identify the root cause'],['一起想出各種可能的方法','Brainstorm different possibilities together'],['建議一個立刻可做的步驟','Suggest a step they can take immediately']]},
{q:['參加一場陌生人的聚會，你通常⋯⋯','At a gathering where you know nobody, you usually…'],a:[['找一兩個人，慢慢聊深入一點','Find one or two people for a deeper conversation'],['先觀察環境和大家的互動','Observe the setting and interactions first'],['主動自我介紹，認識更多人','Introduce yourself and meet lots of people'],['找有共同目標的人交流','Connect with people who share your goals']]},
{q:['收到模糊的工作指示時，你會⋯⋯','When you receive vague instructions, you…'],a:[['和對方確認彼此的期待','Check expectations together'],['要求明確規格與判斷標準','Ask for clear specifications and criteria'],['把它當成發揮創意的空間','See it as room to be creative'],['先決定方向，邊做邊調整','Choose a direction and adjust as you go']]},
{q:['面對緊迫的期限，你比較容易⋯⋯','When a deadline is tight, you are most likely to…'],a:[['照顧團隊氣氛，一起度過壓力','Support team morale through the pressure'],['仔細檢查，避免重要錯誤','Check carefully to prevent critical errors'],['鼓勵大家，想出靈活的替代方案','Encourage others and invent flexible alternatives'],['排好優先次序，加快執行','Prioritize and speed up execution']]},
{q:['哪一句稱讚最像你？','Which compliment sounds most like you?'],a:[['你總是讓人感到被理解','You always make people feel understood'],['你能注意到別人忽略的細節','You notice details other people miss'],['和你一起做事很有活力','Working with you is energizing'],['你很能把事情推進到完成','You really get things done']]},
{q:['會議陷入沉默，你會⋯⋯','When a meeting falls silent, you…'],a:[['溫和地邀請尚未發言的人','Gently invite someone who has not spoken'],['整理已知資訊，提出具體問題','Summarize what is known and ask a specific question'],['分享一個新想法帶動討論','Share a new idea to spark discussion'],['提出決策選項，推動下一步','Offer decision options and move to the next step']]},
{q:['學習一項新技能，你偏好⋯⋯','When learning a new skill, you prefer…'],a:[['有人陪伴，一起練習','Practicing together with someone supportive'],['先看清楚原理和步驟','Understanding the principles and steps first'],['用有趣的方式自由嘗試','Experimenting in playful, interesting ways'],['直接實作，挑戰一個目標','Jumping in and tackling a goal']]},
{q:['計畫臨時改變時，你最先想到⋯⋯','When plans change unexpectedly, your first thought is…'],a:[['這會如何影響大家？','How will this affect everyone?'],['哪些細節需要重新確認？','Which details need to be checked again?'],['會不會有更有趣的可能？','Could this open up an exciting possibility?'],['怎樣最快回到目標上？','How do we get back on track quickly?']]},
{q:['給別人回饋時，你通常⋯⋯','When giving someone feedback, you usually…'],a:[['注意措辭，顧及對方感受','Choose words carefully and consider their feelings'],['提供具體例子與事實','Provide specific examples and facts'],['強調亮點，鼓勵更多嘗試','Highlight positives and encourage experimentation'],['直接指出可改善的地方','Point out what can improve directly']]},
{q:['你最喜歡哪種合作氣氛？','Which team atmosphere do you prefer?'],a:[['彼此信任，互相照顧','Trusting and supportive'],['有條理，標準清楚','Organized, with clear standards'],['開放熱鬧，可以自由交流','Lively, open and conversational'],['自主高效，重視成果','Independent, efficient and results-focused']]},
{q:['做一個重要選擇之前，你通常⋯⋯','Before making an important choice, you usually…'],a:[['和信任的人聊聊影響','Discuss its impact with people you trust'],['比較選項的利弊與證據','Compare pros, cons and evidence'],['想像每個選項帶來的可能性','Imagine the possibilities each option offers'],['挑選最能達成目標的選項','Pick the option that best achieves your goal']]},
{q:['團隊有衝突時，你較常扮演⋯⋯','During a team conflict, you most often become…'],a:[['幫大家找到共識的協調者','The mediator finding common ground'],['釐清事實與誤解的分析者','The analyst clarifying facts and misunderstandings'],['緩和氣氛、帶來新角度的人','The person easing tension with a fresh perspective'],['推動解決方案的決策者','The decision-maker driving a solution']]},
{q:['向別人介紹一個點子，你會先說⋯⋯','When introducing an idea, you lead with…'],a:[['它能如何幫助大家','How it can help people'],['它的原理與支持資料','How it works and the supporting information'],['它令人興奮的願景','The exciting vision behind it'],['它能帶來什麼成果','The results it can deliver']]},
{q:['工作告一段落，什麼最讓你滿足？','After finishing a task, what feels most satisfying?'],a:[['大家都覺得合作愉快','Everyone enjoyed working together'],['成果準確，而且品質可靠','The work is accurate and reliable'],['過程有趣，也帶來新靈感','The process was fun and inspiring'],['完成目標，而且有實際成效','The goal was met with a tangible impact']]},
{q:['被邀請負責一項任務時，你先問⋯⋯','When asked to take on a task, you first ask…'],a:[['我會和誰合作？','Who will I be working with?'],['有哪些要求與限制？','What are the requirements and constraints?'],['有多少空間嘗試新方法？','How much room is there to try new approaches?'],['要達到什麼目標，何時完成？','What is the goal and when is it due?']]},
{q:['朋友遇到挫折，你通常會⋯⋯','When a friend faces a setback, you usually…'],a:[['陪在身邊，讓他慢慢說','Stay with them and let them talk'],['一起分析原因與可行選項','Analyze the causes and options together'],['幫他看見希望和新的可能','Help them see hope and new possibilities'],['協助訂下一個行動計畫','Help them make an action plan']]},
{q:['最自然的你，溝通時比較重視⋯⋯','When you are being yourself, your communication emphasizes…'],a:[['讓彼此安心、感到被尊重','Helping people feel safe and respected'],['讓訊息準確、清楚而完整','Making information accurate, clear and complete'],['讓交流充滿活力與靈感','Filling conversations with energy and inspiration'],['讓事情有方向、有下一步','Giving things direction and a next step']]}
];
export function score(answers:number[]) { const counts=[0,0,0,0]; answers.forEach(a=>{if(Number.isInteger(a)&&a>=0&&a<4)counts[a]++}); return counts.map(n=>n*5); }
export function validPaymentLink(value:string) { try { const u=new URL(value); return u.protocol==='https:' && u.hostname==='buy.stripe.com' && u.pathname.length>1 && !u.pathname.startsWith('/test_') && !u.username && !u.password; } catch { return false; } }
const defaultPaymentLink='https://buy.stripe.com/28E14gdBRfTy4t61Vh73G00';
const configuredLink=process.env.NEXT_PUBLIC_STRIPE_PAYMENT_LINK || defaultPaymentLink;
export const paymentLink=validPaymentLink(configuredLink)?configuredLink:'';

