import type {ContentPage} from './editorial';
export const relationshipGuides:ContentPage[]=[
 {path:'/guides/expressing-relationship-needs',kind:'guide',title:['怎樣向伴侶說明需要：把期待變成可回應的請求','How to express relationship needs as answerable requests'],description:['從回訊息、陪伴到分工，用具體對話練習說明需要、聆聽差異與協商界線，單身也能用來整理期待。','Practice requests about messages, time together and shared tasks, with examples for listening, boundaries and expectations whether single or partnered.'],links:['/tests/love-personality','/guides/infp-love','/dope/dove','/guides/communication-differences'],sections:[
  {heading:['把觀察和解釋分開','Separate observation from interpretation'],body:['「你整晚沒有回覆」是可以確認的事情，「你根本不在乎我」則是解釋。先描述一個具體時段，再說自己的感受與需要，例如：「昨天我不知道你何時回來，有點擔心。我想有個大概時間。」這不代表對方必須隨時在線，而是讓對話有可核實的起點。','“You did not reply last evening” is an observation; “You do not care about me” is an interpretation. Name the specific period, then your feeling and need: “I felt worried not knowing when you would return. A rough time would help.” This does not require constant availability; it gives the conversation a checkable starting point.']},
  {heading:['請求要容許回答','A request needs room for an answer'],body:['「你應該更主動」很難知道怎樣做到。可以改成：「這週你願意選一天一起散步嗎？」對方可以答應、拒絕或提出其他時間。若只有一個被允許的答案，那就更像要求服從；共同安排需要雙方都有選擇。','“Be more proactive” offers little guidance. Try “Would you choose an evening for a walk this week?” The other person can agree, decline or suggest another time. If only one answer is acceptable, the request leaves little room for cooperation.']},
  {heading:['付出與想收到的方式可能不同','Giving and receiving can differ'],body:['你可能習慣幫忙做事，卻最希望收到的是專注聆聽。不要只用自己常做的事推測對方需要甚麼。各自完成兩句話：「我常用……表達在乎」和「我累的時候希望……」。找出一項可以互相嘗試的行動，而不是比較誰付出更多。','You may usually help with tasks but most want attentive listening yourself. Do not infer another person’s needs solely from your way of giving. Each finish “I often show care by…” and “When tired, I would appreciate…”. Choose one action to try rather than ranking who contributes more.']},
  {heading:['分工分歧：談任務，也談責任','For shared tasks, discuss ownership too'],body:['「你提醒我就會做」可能仍把記住和追蹤的工作留給一方。可以把買菜拆成查存貨、列清單、購買及收拾，討論由誰完整負責哪部分。先試行一週，再按實際時間調整，不必把第一次協議當成永久規則。','“I will do it if you remind me” may leave remembering and tracking with one person. Break shopping into checking supplies, making a list, buying and putting away. Discuss ownership of whole parts, try a week and adjust to the actual workload. The first agreement need not be permanent.']},
  {heading:['暫停衝突時保留回來的時間','Make a pause include a return'],body:['情緒太滿時，可以說：「我想繼續談，但現在難以聽清楚。我們晚飯後再談十五分鐘好嗎？」休息不是讓問題消失，也不應拿沉默懲罰對方。回來後先確認彼此理解，再選一個小改變。若對話出現威脅或控制，測驗不能代替實際支持與安全安排。','When overwhelmed, try “I want to continue, but I cannot listen well right now. Could we return to this for fifteen minutes after dinner?” A break does not erase the issue or justify punishing silence. On returning, check understanding and choose one small change. A quiz cannot replace practical support or safety arrangements where threats or control are involved.']},
  {heading:['用測驗開話題，不替對方下結論','Use a quiz to open a conversation'],body:['戀愛人格結果可以提示你偏好表達、陪伴、照顧還是成長，但比例不是需求的完整清單。請對方選一段符合、一段不符合的描述，再分享真實例子。最後約定一件下週願意試的事，比要求對方符合某種類型更有用。','A love quiz can prompt reflection on expression, companionship, practical care or growth, but its percentages are not a complete list of needs. Each choose one description that fits and one that does not, with real examples. Agree on one experiment for next week rather than asking someone to conform to a type.']},
 ]},
 {path:'/guides/infp-love',kind:'guide',title:['INFP 戀愛反思：理想、空間與說得清楚的期待','INFP relationship reflection: ideals, space and clear expectations'],description:['以 INFP 輪廓作起點，探索理想與日常安排的落差、獨處需要和衝突中的表達。沒有最佳配對排行。','Use the INFP profile to reflect on ideals, everyday arrangements, solitude and disagreement, without a ranking of ideal partners.'],links:['/personality/infp','/personality/infj','/tests/love-personality','/guides/expressing-relationship-needs','/tests/personality-16'],sections:[
  {heading:['有共鳴，不等於日常自動合拍','Resonance does not settle everyday arrangements'],body:['如果 INFP 輪廓中的個人意義與想像令你有共鳴，你可能重視被理解的感覺。然而聊得深入，不代表對金錢、聯絡頻率或獨處時間有相同期待。試著從「我們很像」走到一個具體問題，例如週末想怎樣安排，讓關係也容納實際差異。','If the INFP profile’s emphasis on personal meaning and imagination resonates, feeling understood may matter to you. Deep conversation does not settle expectations about money, contact or time alone. Move from “we are alike” to one concrete question, such as how to spend weekends, leaving room for practical differences.']},
  {heading:['理想可以指方向，不必成為考卷','Let an ideal guide you without becoming a test'],body:['理想中的伴侶可能總知道何時安慰、何時留空間，但真實的人需要資訊。把「懂我的人應該知道」改成「這件事對我重要，因為……」。若期待尚未說出口，先溝通，再觀察對方願意如何回應，而不是用一次失望評斷整段關係。','An imagined partner may always know when to comfort and when to give space; a real person needs information. Replace “someone who understands me should know” with why this matters to you. Communicate an unspoken expectation before treating a disappointment as a verdict on the relationship.']},
  {heading:['獨處與連結可以一起安排','Plan solitude and connection together'],body:['想安靜整理不代表不愛對方，但突然消失容易留下不確定。可以說：「我今晚想自己待一會，明早想和你吃早餐。」也詢問對方需要甚麼基本交代。這是協商節奏，不是用人格類型取得免溝通的理由。','Wanting quiet reflection need not mean a lack of affection, but disappearing can leave uncertainty. Try “I would like tonight to myself and breakfast with you tomorrow.” Ask what basic reassurance would help. This negotiates a rhythm rather than using a type as permission not to communicate.']},
  {heading:['被誤解時，縮小到一件可回應的事','When misunderstood, focus on one answerable issue'],body:['如果一句玩笑觸動了重視的價值，先指出具體部分：「你剛才模仿我的作品，讓我覺得用心被取笑；下次可以先問我是否介意嗎？」對方可以理解影響，也可能補充不同用意。兩者能同時存在，修復不必先證明誰完全正確。','If a joke touches a value you care about, name the part: “Imitating my work felt like making fun of my effort. Could you ask whether I mind next time?” The person can understand the impact and explain a different intention. Repair does not require proving one person entirely right.']},
  {heading:['沒有四字母保證適合','Four letters cannot guarantee a good relationship'],body:['不論對方是 ENFJ、INFJ 或任何其他類型，都不能只靠代碼預測信任與相處。觀察願不願意尊重界線、討論責任和修正行為，並留意描述不符合你的地方。人格文章提供問題，不應替你決定留下或離開。','Whether someone is ENFJ, INFJ or another type, letters cannot predict trust or how you will live together. Observe respect for boundaries, responsibility and willingness to change behavior, and notice where the profile does not fit. An article offers questions; it should not decide whether you stay or leave.']},
  {heading:['本週的小練習','A small experiment this week'],body:['寫下一個尚未說清楚的期待，把它改成有時間、有行動而容許拒絕的請求。聽完回應後，記下哪些地方和想像不同。你也可以先做戀愛人格測驗，再用其中一項提示比較自己喜歡付出和希望收到的方式。','Write one unspoken expectation as a request with a time, an action and room to decline. After hearing the response, note how it differs from your assumptions. You can also take the love quiz and use one prompt to compare the care you like giving with what you want to receive.']},
 ]},
];
