import type { CSSProperties } from 'react';
import Image from 'next/image';
import { ArrowRight, Feather } from 'lucide-react';
import TwynzoBrand from './twynzo-brand';
import PixelSpace from './pixel-space';
import { tests } from '@/lib/catalog';
import type { Locale } from '@/lib/seo';

export default function Explore({locale, test}:{locale:Locale;test?:typeof tests[number]}) {
 const en=locale==='en',i=en?1:0;
 const t=(zh:string,eng:string)=>en?eng:zh;
 const suffix=test?'/tests/'+test.slug:'';
 const theme={'--accent':test?.color??'#d4c1ff','--wash':test?.wash??'#2a203b'} as CSSProperties;
 return <div className="explore-theme" style={theme}><PixelSpace en={en}/><div className="site-shell explore-shell">
  <header className="topbar"><TwynzoBrand locale={locale}/><div className="header-actions"><a className="catalog-nav" href={`/${locale}`}>{t('探索測驗','Explore tests')}</a><div className="language" aria-label={t('語言','Language')}><a href={'/zh-hant'+suffix} aria-current={!en?'page':undefined}>繁中</a><a href={'/en'+suffix} aria-current={en?'page':undefined}>EN</a></div></div></header>
  <main className="explore-main">
   <section className="explore-hero"><div><div className="sector-label">TWYNZO / SELF-DISCOVERY UNIVERSE</div>{test&&<a className="all-tests" href={`/${locale}`}>{t('← 所有測驗','← All tests')}</a>}<div className="eyebrow">{test?test.tag[i]:t('每一面，都是你','EVERY SIDE IS YOU')}</div><h1>{test?test.name[i]:t('你的內在宇宙，','Your inner universe,')}{!test&&<em>{t('值得慢慢探索。','waiting to be explored.')}</em>}</h1><p>{test?test.description[i]:t('從溝通風格到戀愛與人格，一次小測驗，發現一個新的自己。選一顆星，開始今天的探索。','From communication to love and personality, each little quiz offers a new perspective. Pick a star and begin your exploration.')}</p><div className="explore-meta">{t('中英文版本 · 自我探索 · 依自己的步調','中文 / EN · SELF-REFLECTION · AT YOUR OWN PACE')}</div></div><div className="portal-art" aria-hidden="true"><div className="portal-orbit"/><span className="portal-spark">✦</span>{test?<span className="portal-symbol">{test.symbol}</span>:<Image src="/astronaut-pixel.svg" width={240} height={240} alt=""/>}<span className="portal-caption">{test?'NEXT DESTINATION':'HELLO, EXPLORER'}</span></div></section>
   {!test?<section className="test-catalog" aria-label={t('所有測驗','All tests')}><div className="catalog-heading"><h2>{t('選擇你的探索起點','Choose your starting point')}</h2><span>01 AVAILABLE / 02 COMING SOON</span></div><a href={`/${locale}/dope`} className="featured-test"><div className="featured-copy"><span className="test-status">{t('可立即作答','READY TO EXPLORE')}</span><div className="test-wordmark"><Feather size={24}/> DOPE TEST</div><h2>{t('你的性格，是哪一種鳥？','Which bird are you?')}</h2><p>{t('鴿子、貓頭鷹、孔雀、老鷹。探索四種溝通風格，認識你的獨特比例。','Dove, Owl, Peacock or Eagle. Explore four communication styles and discover your unique blend.')}</p><span className="card-facts">{t('20 題 · 約 4 分鐘 · 免費','20 questions · About 4 minutes · Free')}</span><span className="card-action">{t('開始 DOPE 測驗','Start DOPE test')}<ArrowRight size={18}/></span></div><Image src="/birds-pixel.png" alt={t('像素 Q 版鴿子、貓頭鷹、孔雀和老鷹','Pixel chibi dove, owl, peacock and eagle')} width={1536} height={1024} sizes="(max-width: 700px) 90vw, 500px"/></a><div className="upcoming-grid">{tests.map(item=><a className="upcoming-test" style={{'--accent':item.color,'--wash':item.wash} as CSSProperties} href={`/${locale}/tests/${item.slug}`} key={item.slug}><span className="test-status">{t('即將推出','COMING SOON')}</span><span className="small-planet" aria-hidden="true">{item.symbol}</span><h2>{item.name[i]}</h2><p>{item.description[i]}</p><span className="card-action">{t('搶先了解','Explore the preview')}<ArrowRight size={17}/></span></a>)}</div></section>:<section className="preview-panel"><span className="test-status">{t('即將推出 · 測驗準備中','COMING SOON · IN DEVELOPMENT')}</span><h2>{t('下一段探索，正在準備中。','Your next exploration is taking shape.')}</h2><p>{t('這裡是測驗預告頁。完整題目、計分方式與結果解讀尚未開放。你可以先從下面的小問題，留意日常中的自己。','This is a preview page. The full questions, scoring and result interpretation are not available yet. For now, use the reflection below to notice yourself in everyday life.')}</p><div className="preview-topics">{test.topics.map((topic,n)=><div key={topic[1]}><span>0{n+1}</span><h3>{topic[i]}</h3></div>)}</div><div className="reflection"><span>{t('留一個問題給自己','A MOMENT FOR YOURSELF')}</span><h3>{test.prompt[i]}</h3><p>{t('不用急著找答案，也沒有標準答案。','There is no rush, and no right answer.')}</p></div>{test.slug==='personality-16'&&<p className="preview-note">{t('本頁為以 MBTI 概念為靈感的原創探索企劃，並非官方 MBTI® 評估，與其權利人無關。','An original exploration inspired by MBTI concepts. This is not the official MBTI® assessment and is not affiliated with its rights holders.')}</p>}<a className="primary" href={`/${locale}/dope`}>{t('先玩 DOPE 鳥類性格測驗','Try the DOPE bird test')}<ArrowRight size={17}/></a></section>}
  </main><footer><span>Twynzo © 2026</span><p>{t('給每一個想更認識自己的人。測驗供自我探索與交流參考，不是心理診斷。','For everyone curious about themselves. These explorations are for reflection and conversation, not psychological diagnosis.')}</p></footer>
 </div></div>;
}
