'use client';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import Image from 'next/image';
import {ArrowLeft,ArrowRight,Check,Coffee,Copy,RotateCcw,Share2,Users} from 'lucide-react';
import {RadioGroup,RadioGroupItem} from './ui/radio-group';
import {Progress} from './ui/progress';
import PixelSpace from './pixel-space';
import TwynzoBrand from './twynzo-brand';
import ResultImage from './result-image';

import {tests} from '@/lib/catalog';
import {axes,calculate,getQuestions,loveStyles,typeNames,preferenceNotes,validTestAnswers,type TestSlug} from '@/lib/personality-tests';
import {paymentLink} from '@/lib/quiz';
import type {Locale} from '@/lib/seo';

export default function PersonalityQuiz({locale,slug,children,navigation}:{locale:Locale;slug:TestSlug;children?:React.ReactNode;navigation?:React.ReactNode}){
 const test=tests.find(t=>t.slug===slug)!,en=locale==='en',lang=en?1:0,isType=slug==='personality-16';
 const questions=getQuestions(slug),length=questions.length,path=`/${locale}/tests/${slug}`;
 const t=(zh:string,eng:string)=>en?eng:zh;
 const [answers,setAnswers]=useState<number[]>(Array(length).fill(-1));
 const [step,setStep]=useState(0),[done,setDone]=useState(false),[ready,setReady]=useState(false);
 const [count,setCount]=useState<number|null>(null),[countError,setCountError]=useState(false);
 const [message,setMessage]=useState(''),[manualUrl,setManualUrl]=useState('');
 const heading=useRef<HTMLHeadingElement>(null);
 const endpoint='/api/tests/'+slug+'/completions';
 useEffect(()=>{
  try{const raw=sessionStorage.getItem('twynzo-transfer-'+slug);sessionStorage.removeItem('twynzo-transfer-'+slug);if(raw){const v=JSON.parse(raw);if(Date.now()-v.at<60000&&Array.isArray(v.answers)&&v.answers.length===length&&v.answers.every((n:unknown)=>Number.isInteger(n)&&Number(n)>=-1&&Number(n)<=3)&&Number.isInteger(v.step)&&v.step>=0&&v.step<length){setAnswers(v.answers);setStep(v.step);setDone(v.done===true&&validTestAnswers(slug,v.answers));}}}catch{}
  setReady(true);void fetch('/api/session',{method:'POST'}).catch(()=>{});
  fetch(endpoint).then(r=>{if(!r.ok)throw Error();return r.json();}).then(v=>setCount(v.total)).catch(()=>setCountError(true));
 },[slug,length,endpoint]);
 useEffect(()=>{if(!ready||!done)return;let alive=true;fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({answers})}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(v=>{if(alive){setCount(v.total);setCountError(false);}}).catch(()=>{if(alive)setCountError(true);});return()=>{alive=false;};},[ready,done,answers,endpoint]);
 useEffect(()=>{if(step||done)heading.current?.focus();},[step,done]);
 function switchLocale(event:React.MouseEvent<HTMLAnchorElement>,next:Locale){if(event.ctrlKey||event.metaKey||event.shiftKey||event.altKey)return;try{sessionStorage.setItem('twynzo-transfer-'+slug,JSON.stringify({answers,step,done,at:Date.now()}));}catch{}event.preventDefault();window.location.assign(`/${next}/tests/${slug}`);}
 const result=done?calculate(slug,answers):null;
 const leaders=result&&!isType?loveStyles.filter((_,i)=>result.values[i]===Math.max(...result.values)):[];
 const title=result?(isType?result.code:leaders.map(s=>s.name[lang]).join(' + ')):'';
 async function share(copy=false){const url=window.location.origin+(isType&&result&&typeNames[result.code]?`/${locale}/personality/${result.code.toLowerCase()}`:path),text=t(`我的${test.name[0]}結果是 ${title}！一起來探索：`,`My ${test.name[1]} result is ${title}! Explore yours:`);setMessage('');try{if(!copy&&navigator.share){await navigator.share({title:test.name[lang],text,url});setMessage(t('已開啟分享','Share opened'));}else if(navigator.clipboard){await navigator.clipboard.writeText(text+' '+url);setMessage(t('已複製，貼給朋友一起玩！','Copied — share it with a friend!'));}else{setManualUrl(url);}}catch(e){if((e as Error).name!=='AbortError'){setManualUrl(url);setMessage(t('請複製下方連結','Copy the link below'));}}}
 const theme={'--accent':test.color,'--wash':test.wash} as CSSProperties;
 return <div className="explore-theme themed-quiz" style={theme}><PixelSpace en={en}/><div className="site-shell"><header className="topbar"><TwynzoBrand locale={locale}/><div className="header-actions"><a className="coffee-nav" href="#coffee" aria-label={t('請我喝咖啡','Buy me a coffee')}><Coffee size={17}/><span>{t('請我喝咖啡','Buy me a coffee')}</span></a><div className="language"><a href={`/zh-hant/tests/${slug}`} aria-current={!en?'page':undefined} onClick={e=>switchLocale(e,'zh-hant')}>繁中</a><a href={`/en/tests/${slug}`} aria-current={en?'page':undefined} onClick={e=>switchLocale(e,'en')}>EN</a></div></div></header>
 <main id="main-content">{navigation}<div className="intro"><a className="all-tests" href={`/${locale}/tests`}>{t('← 所有測驗','← All tests')}</a><div className="test-wordmark">{test.symbol} {isType?'PERSONALITY / 16':'LOVE / PERSONALITY'}</div><div className="eyebrow">{test.tag[lang]}</div><h1>{test.name[lang]}</h1><p>{test.description[lang]} {t('選擇最像平常自己的反應，沒有標準答案。','Choose what feels most like your usual self. There are no right answers.')}</p><div className="hero-orbit" aria-hidden="true"><div className="orbit-ring"/><Image src="/astronaut-pixel.svg" alt="" width={240} height={240} className="hero-astronaut"/><span className="orbit-coordinate">TWYNZO / INNER SPACE</span></div><div className="community"><Users size={18}/><div><strong>{count===null?t('一起探索更多面的自己','Explore another side of yourself'):t(`已有 ${count.toLocaleString()} 位完成測試`,`${count.toLocaleString()} quiz completions`)}</strong>{countError&&<small role="status">{t('計數暫時無法同步，測驗仍可正常使用。','Count temporarily unavailable. Your quiz still works.')}</small>}</div></div><div className="facts"><span>{length} {t('道題目','questions')}</span><span>{t('約 4–5 分鐘','About 4–5 minutes')}</span><span>{t('免費・不需註冊','Free · No sign-up')}</span></div><p className="quiz-intro-note">{isType?t('原創偏好探索，並非官方 MBTI® 評估。','Original preference exploration, not the official MBTI® assessment.'):t('不論是否正在戀愛，都可依過往經驗或理想的相處方式作答。','Whether or not you are in a relationship, use past experience or how you would like to connect.')}</p></div>
 <div className={'workspace '+(done?'finished':'in-flight')}><section className="quiz-card" aria-label={test.name[lang]}>{!done?<><div className="quiz-meta"><span className="window-dots" aria-hidden="true">▪ ▪ ▪</span><span>{t('探索你的風格','EXPLORE YOUR STYLE')}</span><span>{String(step+1).padStart(2,'0')} / {length}</span></div><div className="space-progress"><div className="starfield" aria-hidden="true">✦ · ˚ · ✧ · ˚ · ✦</div><div className="astronaut-position" style={{left:answers.filter(n=>n>=0).length/length*100+'%'}} aria-hidden="true"><Image src="/astronaut-pixel.svg" alt="" width={100} height={100} className="astronaut"/></div><Progress value={answers.filter(n=>n>=0).length/length*100} aria-label={t('作答進度','Quiz progress')}/><span className="mission-caption">{answers.filter(n=>n>=0).length} / {length}</span></div><div className="question-content"><span className="question-kicker">{t('想像一下⋯⋯','PICTURE THIS…')}</span><h2 ref={heading} tabIndex={-1} id="test-question">{questions[step].q[lang]}</h2><p className="question-hint">{t('選擇最符合你自然反應的一項。','Choose what feels most natural to you.')}</p><RadioGroup aria-labelledby="test-question" value={answers[step]<0?'':String(answers[step])} onValueChange={v=>setAnswers(a=>a.map((n,i)=>i===step?Number(v):n))} className="choices">{[0,1,2,3].map(n=>{const choice=isType?n:(n+step)%4;return <label key={step+'-'+choice} className={'choice '+(answers[step]===choice?'selected':'')}><RadioGroupItem value={String(choice)} aria-label={questions[step].options[choice][lang]}/><span className="choice-letter">{'ABCD'[n]}</span><span>{questions[step].options[choice][lang]}</span>{answers[step]===choice&&<Check size={19} className="choice-check"/>}</label>;})}</RadioGroup></div><div className="quiz-bottom"><button className="back" disabled={step===0} onClick={()=>setStep(s=>s-1)}><ArrowLeft size={17}/>{t('上一題','Back')}</button><button className="primary" disabled={answers[step]<0} onClick={()=>step===length-1?setDone(true):setStep(s=>s+1)}>{step===length-1?t('查看我的結果','See my results'):t('下一題','Next question')}<ArrowRight size={18}/></button></div></>:result&&<div className="results"><div className="eyebrow">{t('你的探索結果','YOUR EXPLORATION RESULT')}</div><h2 ref={heading} tabIndex={-1}>{title}</h2>{isType&&<p>{typeNames[result.code]?.[lang]??t('部分面向得分相同，X 代表未呈現明確偏好。','Some dimensions are tied; X indicates no clear preference.')}</p>}{!isType&&<p>{leaders.length>1?t('最高分並列，呈現混合戀愛風格。','Your top scores are tied: you show a blend of love styles.'):leaders[0].desc[lang]}</p>}
 <div className="score-list">{result.values.map((value,i)=><div key={i}><div className="score-label"><span>{isType?`${axes[i].code[0]} ${axes[i].left[lang]} / ${axes[i].code[1]} ${axes[i].right[lang]}`:loveStyles[i].name[lang]}</span><strong>{isType?`${value}% / ${100-value}%`:`${value}%`}</strong></div><div className="score-track"><span style={{width:value+'%'}}/></div>{isType&&<p className="axis-note">{Math.abs(value-50)<=11?t('兩端偏好接近，可多觀察不同情境。','These preferences are close. Notice how they vary by situation.'):t('本次回答較偏向：','Your answers lean toward: ')}{Math.abs(value-50)>11&&axes[i][value>50?'left':'right'][lang]}</p>}</div>)}</div>
 <p className="method">{isType?t('每個面向 6 題；四個選項以 +3、+1、−1、−3 計分，反向題反轉。兩端比例是分數的線性換算，不是人口百分位或準確率；相同分數以 X 呈現。','Six items per dimension score +3, +1, −1 or −3, with reverse scoring where appropriate. Paired percentages are a linear score conversion, not population percentiles or accuracy. Exact ties display X.'):t('每題為所選風格加 1 分；百分比是該風格的選擇次數 ÷ 20。這是本次相處偏好的輪廓，不是依附類型、配對成功率或診斷。','Each choice adds one point to a style. Percentages are selections divided by 20. This describes your preferences, not attachment type, compatibility or a diagnosis.')}</p>
 {isType?axes.map((axis,i)=><div className="advice" key={axis.code[0]}><h3>{axis.name[lang]}</h3><p>{result.values[i]===50?t("這個面向兩端分數相同，先觀察不同場合的自己，不需要急著定型。","Both sides are tied here. Observe yourself across situations without rushing to choose a label."):preferenceNotes[axis.code[result.values[i]>50?0:1]][lang]}</p><p>{axis.tip[lang]}</p></div>):leaders.map(style=><div className="advice" key={style.code}><h3>{style.name[lang]} · {t('相處提示','Connection tip')}</h3><p>{style.tip[lang]}</p></div>)}
 {isType&&result.candidates.length>1&&<div className="advice"><h3>{t('可繼續探索的類型','Types you can explore further')}</h3><p>{result.candidates.map((code,i)=><span key={code}>{i>0?' · ':''}<a href={`/${locale}/personality/${code.toLowerCase()}`}>{code}</a></span>)}</p><p>{t('因部分面向並列，保留所有可能組合，沒有替你強行選一型。','Tied dimensions leave multiple possible combinations.')}</p></div>}
 {isType&&typeNames[result.code]&&<p><a href={`/${locale}/personality/${result.code.toLowerCase()}`}>{t('閱讀 ', 'Read the ')}{result.code}{t(' 的完整探索文章',' reflection profile')} →</a></p>}<div className="share-panel"><h3>{t('邀請朋友一起探索','Explore with a friend')}</h3><p>{t('分享彼此的結果，開啟一段新的對話。','Share your results and start a new conversation.')}</p><div className="share-actions"><button className="primary" onClick={()=>share()}><Share2 size={17}/>{t('分享給朋友','Share with friends')}</button><button className="secondary" onClick={()=>share(true)}><Copy size={17}/>{t('複製連結','Copy link')}</button></div><ResultImage values={result.values} en={en} card={{brand:isType?'TWYNZO / PERSONALITY 16':'TWYNZO / LOVE PERSONALITY',title:isType?result.code:leaders.length===1?leaders[0].name[lang]:t('混合戀愛風格','Blended love style'),subtitle:isType?t('偏好是起點，不是限制。','Preferences are a starting point, not a limit.'):t('用自己的方式，建立連結。','Find your own way to connect.'),labels:isType?axes.map(a=>a.code.join(' / ')):loveStyles.map(s=>s.name[lang]),displayValues:result.values.map(v=>isType?`${v}% / ${100-v}%`:`${v}%`),accent:test.color,path}}/><p role="status">{message}</p>{manualUrl&&<input readOnly aria-label={t('分享連結','Share link')} value={manualUrl} onFocus={e=>e.currentTarget.select()}/>}</div><button className="primary" onClick={()=>{setAnswers(Array(length).fill(-1));setStep(0);setDone(false);setMessage('');setManualUrl('');}}><RotateCcw size={17}/>{t('重新測驗','Take it again')}</button></div>}</section>
 {done&&<aside className="bird-guide"><div className="type-guide-symbol" aria-hidden="true">{test.symbol}</div><div className="guide-title">{isType?t('四個面向，更多可能','FOUR DIMENSIONS. MANY POSSIBILITIES.'):t('四種方式，表達在乎','FOUR WAYS TO SHOW YOU CARE')}</div><p>{t('每一種偏好都有價值，也能隨經驗與情境展現不同面貌。','Every preference has value and can show up differently across experiences and situations.')}</p>{isType?axes.map(a=><div className="bird-row" key={a.code[0]}><span className="bird-initial">{a.code.join('/')}</span><div><h3>{a.name[lang]}</h3><p>{a.tip[lang]}</p></div></div>):loveStyles.map(s=><div className="bird-row" key={s.code}><span className="bird-initial">{s.code}</span><div><h3>{s.name[lang]}</h3><p>{s.desc[lang]}</p></div></div>)}<div className="guide-note">{t('結果不是標籤；理解差異，比評分誰更好更重要。','Results are not labels. Understanding differences matters more than ranking them.')}</div></aside>}</div>
 <section className="coffee-card" id="coffee"><div className="coffee-icon"><Coffee size={27}/></div><div><h2>{t('喜歡這個小測驗？','Enjoyed this little discovery?')}</h2><p>{t('請我喝杯咖啡，支持更多自我探索的小工具。','A little coffee helps keep these explorations growing.')}</p></div><div className="coffee-action">{paymentLink&&<a className="coffee-button" href={paymentLink} target="_blank" rel="noopener noreferrer">{t('請我喝咖啡','Buy me a coffee')} <strong>US$3</strong><ArrowRight size={16}/></a>}<span>{t('透過 Stripe 安全付款・自願贊助','Secure payment with Stripe · Optional support')}</span></div></section>{children}</main>
 <footer><span>Twynzo © 2026</span><p>{t('原創自我探索題目，並非官方或經驗證的心理評估；不適用於診斷或招聘決策。答案不儲存於資料庫；完成時僅即時驗證答案，以匿名瀏覽器識別碼為各測驗去重計數。語言切換暫存答案最多 60 秒。','Original self-reflection questions, not an official or validated psychological assessment. Not for diagnosis or hiring. Answers are validated on completion but not stored in the database. Anonymous browser identifiers deduplicate each test. Language switching temporarily stores answers for up to 60 seconds.')}</p></footer></div></div>;
}
