import type {Locale} from '@/lib/seo';
import {typeProfiles} from '@/lib/type-content';
import SearchGuide from './search-guide';
import {ResourceLinks} from './content-navigation';
export default function QuizReading({locale,kind}:{locale:Locale;kind:'dope'|'personality-16'|'love-personality'}){
 const en=locale==='en',love=kind==='love-personality';
 return <div className="quiz-reading">{!love&&<SearchGuide en={en} kind={kind==='dope'?'dope':'mbti'}/>}<section className="search-guide">
 {love?<><h2>{en?'What does the love personality quiz explore?':'戀愛人格測驗在探索甚麼？'}</h2><p>{en?'Twenty original situations invite you to reflect on how you express affection, spend time together, offer practical help and support shared growth. It compares these choices in your answers; it does not identify attachment disorders or predict relationship success.':'20 道原創情境題邀請你觀察表達在乎、共同相處、實際協助與支持成長的方式。結果比較這些選擇在本次作答的比例，不會辨識依附障礙，也不預測戀愛成功率。'}</p><h3>{en?'Can I take it while single?':'單身也可以做嗎？'}</h3><p>{en?'Yes. Think about past experiences or the kind of connection you would like to build. Use a similar reference throughout the quiz; switching between an ideal partner and a current conflict may make your result harder to interpret.':'可以。你可以回想過往經驗，或希望建立的相處方式。整份測驗盡量使用相近的參考情境；若不斷在理想關係和眼前衝突之間切換，結果可能較難理解。'}</p><h3>{en?'How should I use a mixed result?':'混合結果應該怎樣看？'}</h3><p>{en?'A tie means you selected more than one style equally often. None is a better way to care. Ask which gestures you enjoy giving and which you want to receive; the answers can differ. A low share does not mean you cannot use that approach.':'同分代表你選擇某幾種方式的次數相同，沒有哪一種更好。可以分別問自己喜歡怎樣付出、希望怎樣被對待；兩者未必一樣。較低比例也不代表你不懂使用該方式。'}</p><h3>{en?'Does this tell me who to date?':'結果會告訴我適合跟誰交往嗎？'}</h3><p>{en?'No. A useful next step is a conversation, not a compatibility ranking: “When you are tired, what kind of support would feel good?” Real needs, boundaries and behavior matter more than matching quiz labels.':'不會。較有用的下一步是對話，而不是配對排名，例如：「你累的時候，怎樣的支持會讓你舒服？」真實需要、界線和行為，比測驗標籤是否相同更重要。'}</p></>:<><h2>{en?'Read beyond your result':'測驗之外，繼續理解自己'}</h2><p>{en?'These original profiles offer examples, blind spots and practical experiments. Compare them with your experience, including where they do not fit.':'這些原創解讀提供日常例子、可能盲點和實用練習。請與自己的經驗比較，也留意不符合的部分。'}</p></>}
 <ResourceLinks locale={locale} paths={kind==='personality-16'?['/personality',...typeProfiles.map(p=>'/personality/'+p.code.toLowerCase()),'/guides/read-personality-results','/methodology']:kind==='dope'?['/dope/dove','/dope/owl','/dope/peacock','/dope/eagle','/guides/communication-differences','/methodology']:['/guides/communication-differences','/guides/read-personality-results','/dope','/tests/personality-16','/methodology']}/>
 </section></div>;
}
