export default function SearchGuide({en,kind}:{en:boolean;kind:'home'|'mbti'|'dope'}){
 const root=en?'/en':'/zh-hant';
 return <section className="search-guide" aria-label={en?'Personality test guide':'人格測試指南'}>
 <h2>{kind==='mbti'?(en?'What is MBTI? Understanding 16 personality types':'MBTI 是什麼？認識 16 型人格'):kind==='dope'?(en?'What is the DOPE TEST?':'DOPE TEST 是什麼？'):(en?'Personality tests: where should you start?':'人格測試：從哪裡開始認識自己？')}</h2>
 {kind==='mbti'?<><p>{en?'MBTI describes preferences through four pairs: Extraversion–Introversion, Sensing–Intuition, Thinking–Feeling, and Judging–Perceiving. Combining a preference from each pair creates a four-letter type such as INFP or ESTJ, for 16 possible combinations.':'MBTI 以四組偏好描述人格：外向與內向、實感與直覺、思考與情感、判斷與感知。每組取一個偏好，組成 INFP、ESTJ 等四字母類型，共有 16 種組合。'}</p><div className="dimension-grid">{(en?[['E / I','Extraversion / Introversion','How you tend to direct attention: toward the outside world or your inner world.'],['S / N','Sensing / Intuition','How you tend to take in information: concrete details or patterns and possibilities.'],['T / F','Thinking / Feeling','How you tend to reach decisions: logical criteria or values and people considerations.'],['J / P','Judging / Perceiving','How you tend to approach the outside world: structure and closure or flexibility and openness.']]:[['E / I','外向 / 內向','留意你較自然地把注意力放在外部世界，還是內在的思考與經驗。'],['S / N','實感 / 直覺','留意你較著重具體細節與經驗，還是模式、連結與可能性。'],['T / F','思考 / 情感','留意你做決定時較先考慮邏輯準則，還是價值與對人的影響。'],['J / P','判斷 / 感知','留意你面對外部生活時較偏好安排與定案，還是彈性與保留選擇。']]).map(([code,title,description])=><div key={code}><strong>{code}</strong><h3>{title}</h3><p>{description}</p></div>)}</div><p>{en?'A preference is not a measure of ability or a fixed rule for every situation. Introversion does not automatically mean shyness, and Feeling does not mean a lack of logic. Use type language to start a conversation about your habits rather than to limit your choices.':'偏好不是能力高低，也不代表每個情境都會有相同反應。內向不等於害羞，情感偏好也不等於缺乏邏輯。你可以用類型語言理解日常習慣，但不必用它限制自己的選擇。'}</p><p>{en?'Reference: ':'延伸閱讀：'}<a href="https://www.myersbriggs.org/my-mbti-personality-type/the-mbti-preferences/">{en?'The Myers & Briggs Foundation — MBTI preferences':'Myers & Briggs Foundation：MBTI 偏好介紹'}</a></p></>:<p>{en?'The DOPE TEST uses four bird styles—Dove, Owl, Peacock and Eagle—to explore communication habits. Twynzo offers 20 original everyday scenarios, showing the proportion of answers associated with each style and practical prompts for reflection. The quiz and results are free, in English and Traditional Chinese.':'DOPE TEST（鳥類性格測驗）以鴿子、貓頭鷹、孔雀和老鷹四種風格，協助你觀察溝通習慣。Twynzo 提供 20 道原創生活情境題，結果呈現各風格在本次回答中的比例，並附上溝通提示。測驗與結果免費，支援繁體中文及英文。'}</p>}
 <h3>{en?'How are DOPE and MBTI different?':'DOPE 與 MBTI 有什麼不同？'}</h3><p>{en?'DOPE uses four bird styles as a simple way to discuss communication. MBTI uses four preference pairs to describe 16 type combinations. They are different frameworks: a bird style does not directly translate into a four-letter type. Choose DOPE for a short communication reflection, or read the MBTI guide to learn about type preferences.':'DOPE 用四種鳥類風格談溝通；MBTI 用四組偏好形成 16 種類型。兩者是不同框架，不能把某一種鳥直接換算成某個四字母人格。想快速觀察溝通習慣，可以先玩 DOPE；想了解人格偏好，則可以閱讀 MBTI 指南。'}</p>
 <h3>{en?'Can a personality test define who I am?':'人格測試可以定義我是怎樣的人嗎？'}</h3><p>{en?'Your answers reflect how you see yourself at the time. Context, experience and how you understand a question can affect them. Twynzo’s original quizzes are for self-reflection and discussion, not validated psychological assessments, diagnoses or hiring tools.':'回答反映你當下對自己的理解，也可能受情境、經驗與題目理解影響。Twynzo 的原創測驗供自我探索與交流參考，不是經驗證的心理評估、診斷或招聘工具。'}</p>
 <h3>{en?'Which tests can I take now?':'目前可以做哪些測驗？'}</h3><p>{en?'The DOPE TEST is available now, with free results and a downloadable result card. The love personality and MBTI-inspired 16-type quizzes are still in development; their pages currently provide previews and introductory information.':'DOPE TEST 已開放，可免費查看結果及下載分享圖卡。戀愛人格與以 MBTI 為靈感的 16 型人格測驗仍在準備中，目前頁面提供預告或入門資訊。'}</p>
 <nav className="guide-links"><a href={root+'/dope'}>{en?'Free DOPE TEST →':'免費 DOPE TEST →'}</a><a href={root+'/tests/personality-16'}>{en?'MBTI & 16 types →':'MBTI 與 16 型人格 →'}</a><a href={root}>{en?'All Twynzo tests →':'所有 Twynzo 測驗 →'}</a></nav>
 </section>;
}
